// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserAvgAggregateOutputTypeOutput {
  id: number;
  age: number;
}

import { z } from "zod";

export const UserAvgAggregateOutputTypeOutputSchema = z.object({
  id: z.number().nullable(),
  age: z.number().nullable(),
});
