// Auto-generated by prisma-dto-gen

export interface UserWhereUniqueInput {
  id?: number | null;
  AND_id?: string | null;
  OR_id?: string | null;
  NOT_id?: string | null;
  name_id?: string | null;
  email_id?: string | null;
}