// Auto-generated by prisma-generator-typescript-interfaces

export * from './Query';
export * from './Mutation';
export * from './AggregateUser';
export * from './UserGroupByOutputType';
export * from './AffectedRowsOutput';
export * from './UserCountAggregateOutputType';
export * from './UserAvgAggregateOutputType';
export * from './UserSumAggregateOutputType';
export * from './UserMinAggregateOutputType';
export * from './UserMaxAggregateOutputType';
export * from './User';
export * from './CreateManyUserAndReturnOutputType';