// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserScalarWhereWithAggregatesInput {
  AND: any;
  OR: any;
  NOT: any;
  id: any;
  name: any;
  email: any;
}

import { z } from "zod";

export const UserScalarWhereWithAggregatesInputSchema = z.object({
  AND: z.any(),
  OR: z.array(z.any()),
  NOT: z.any(),
  id: z.any(),
  name: z.any(),
  email: z.any(),
});
