// Auto-generated by prisma-dto-gen (refactored inline)

export interface NestedFloatFilter {
  equals: any;
  in: number[];
  notIn: number[];
  lt: any;
  lte: any;
  gt: any;
  gte: any;
  not: any;
}

import { z } from "zod";

export const NestedFloatFilterSchema = z.object({
  equals: z.number(),
  in: z.array(z.number()),
  notIn: z.array(z.number()),
  lt: z.number(),
  lte: z.number(),
  gt: z.number(),
  gte: z.number(),
  not: z.number(),
});
