// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserCountOrderByAggregateInput {
  id?: any;
  name?: any;
  email?: any;
}

import { z } from "zod";

export const UserCountOrderByAggregateInputSchema = z.object({
  id: z.any().optional(),
  name: z.any().optional(),
  email: z.any().optional(),
});
