// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserCountAggregateOutputTypeOutput {
  id: number;
  name: number;
  email: number;
  _all: number;
}

import { z } from "zod";

export const UserCountAggregateOutputTypeOutputSchema = z.object({
  id: z.number(),
  name: z.number(),
  email: z.number(),
  _all: z.number(),
});
