// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserMaxAggregateOutputTypeOutput {
  id?: number | null;
  name?: string | null;
  email?: string | null;
}

import { z } from "zod";

export const UserMaxAggregateOutputTypeOutputSchema = z.object({
  id: z.number().nullable(),
  name: z.string().nullable(),
  email: z.string().nullable(),
});
