// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserGroupByOutputTypeOutput {
  id: number;
  name: string;
  email: string;
  _count: any;
  _avg: any;
  _sum: any;
  _min: any;
  _max: any;
}