// Auto-generated by prisma-dto-gen

import { z } from "zod";

export const UserOrderByWithRelationInputSchema = z.object({
  id: z.any().nullable(),
  name: z.any().nullable(),
  email: z.any().nullable(),
});
