// Auto-generated by prisma-dto-gen (refactored inline)

export interface OneOrgEventCreateArgs {
  data:
    | {
        org_event_id?: string;
        event_name: string;
        start_time: Date;
        end_time?: any;
        location?: any;
        organization: {
          create?:
            | {
                organization_id?: string;
                name: string;
                description?: any;
                created_on?: Date;
                updated_on?: any;
                is_active?: any;
                members?: {
                  create?:
                    | {
                        membership_id?: any /* max depth reached */;
                        joined_on?: any /* max depth reached */;
                        is_active?: any /* max depth reached */;
                        user_profile: any /* max depth reached */;
                      }
                    | any /* circular reference to OrgMembershipCreateWithoutOrganizationInput */
                    | {
                        membership_id?: any /* max depth reached */;
                        profile_id: any /* max depth reached */;
                        joined_on?: any /* max depth reached */;
                        is_active?: any /* max depth reached */;
                      }
                    | any /* circular reference to OrgMembershipUncheckedCreateWithoutOrganizationInput */;
                  connectOrCreate?:
                    | {
                        where: any /* max depth reached */;
                        create: any /* max depth reached */;
                      }
                    | any /* circular reference to OrgMembershipCreateOrConnectWithoutOrganizationInput */;
                  createMany?: {
                    data: any /* max depth reached */;
                    skipDuplicates?: any /* max depth reached */;
                  };
                  connect?:
                    | {
                        membership_id?: any /* max depth reached */;
                        AND?: any /* max depth reached */;
                        OR?: any /* max depth reached */;
                        NOT?: any /* max depth reached */;
                        organization_id?: any /* max depth reached */;
                        profile_id?: any /* max depth reached */;
                        joined_on?: any /* max depth reached */;
                        is_active?: any /* max depth reached */;
                        organization?: any /* max depth reached */;
                        user_profile?: any /* max depth reached */;
                      }
                    | any /* circular reference to OrgMembershipWhereUniqueInput */;
                };
                records?: {
                  create?:
                    | {
                        record_id?: any /* max depth reached */;
                        title: any /* max depth reached */;
                        details?: any /* max depth reached */;
                        created_on?: any /* max depth reached */;
                        updated_on?: any /* max depth reached */;
                      }
                    | any /* circular reference to OrgRecordCreateWithoutOrganizationInput */
                    | any /* circular reference to OrgRecordUncheckedCreateWithoutOrganizationInput */;
                  connectOrCreate?:
                    | {
                        where: any /* max depth reached */;
                        create: any /* max depth reached */;
                      }
                    | any /* circular reference to OrgRecordCreateOrConnectWithoutOrganizationInput */;
                  createMany?: {
                    data: any /* max depth reached */;
                    skipDuplicates?: any /* max depth reached */;
                  };
                  connect?:
                    | {
                        record_id?: any /* max depth reached */;
                        AND?: any /* max depth reached */;
                        OR?: any /* max depth reached */;
                        NOT?: any /* max depth reached */;
                        organization_id?: any /* max depth reached */;
                        title?: any /* max depth reached */;
                        details?: any /* max depth reached */;
                        created_on?: any /* max depth reached */;
                        updated_on?: any /* max depth reached */;
                        organization?: any /* max depth reached */;
                      }
                    | any /* circular reference to OrgRecordWhereUniqueInput */;
                };
              }
            | {
                organization_id?: string;
                name: string;
                description?: any;
                created_on?: Date;
                updated_on?: any;
                is_active?: any;
                members?: {
                  create?:
                    | any /* circular reference to OrgMembershipCreateWithoutOrganizationInput */
                    | any /* circular reference to OrgMembershipUncheckedCreateWithoutOrganizationInput */;
                  connectOrCreate?: any /* circular reference to OrgMembershipCreateOrConnectWithoutOrganizationInput */;
                  createMany?: any /* circular reference to OrgMembershipCreateManyOrganizationInputEnvelope */;
                  connect?: any /* circular reference to OrgMembershipWhereUniqueInput */;
                };
                records?: {
                  create?:
                    | any /* circular reference to OrgRecordCreateWithoutOrganizationInput */
                    | any /* circular reference to OrgRecordUncheckedCreateWithoutOrganizationInput */;
                  connectOrCreate?: any /* circular reference to OrgRecordCreateOrConnectWithoutOrganizationInput */;
                  createMany?: any /* circular reference to OrgRecordCreateManyOrganizationInputEnvelope */;
                  connect?: any /* circular reference to OrgRecordWhereUniqueInput */;
                };
              };
          connectOrCreate?: {
            where: {
              organization_id?: string;
              AND?:
                | {
                    AND?: any /* max depth reached */;
                    OR?: any /* max depth reached */;
                    NOT?: any /* max depth reached */;
                    organization_id?: any /* max depth reached */;
                    name?: any /* max depth reached */;
                    description?: any /* max depth reached */;
                    created_on?: any /* max depth reached */;
                    updated_on?: any /* max depth reached */;
                    is_active?: any /* max depth reached */;
                    events?: any /* max depth reached */;
                    members?: any /* max depth reached */;
                    records?: any /* max depth reached */;
                  }
                | any /* circular reference to OrganizationWhereInput */;
              OR?: any /* circular reference to OrganizationWhereInput */;
              NOT?: any /* circular reference to OrganizationWhereInput */;
              name?:
                | {
                    equals?: any /* max depth reached */;
                    in?: any /* max depth reached */;
                    notIn?: any /* max depth reached */;
                    lt?: any /* max depth reached */;
                    lte?: any /* max depth reached */;
                    gt?: any /* max depth reached */;
                    gte?: any /* max depth reached */;
                    contains?: any /* max depth reached */;
                    startsWith?: any /* max depth reached */;
                    endsWith?: any /* max depth reached */;
                    mode?: any /* max depth reached */;
                    not?: any /* max depth reached */;
                  }
                | string;
              description?: any;
              created_on?:
                | {
                    equals?: any /* max depth reached */;
                    in?: any /* max depth reached */;
                    notIn?: any /* max depth reached */;
                    lt?: any /* max depth reached */;
                    lte?: any /* max depth reached */;
                    gt?: any /* max depth reached */;
                    gte?: any /* max depth reached */;
                    not?: any /* max depth reached */;
                  }
                | Date;
              updated_on?: any;
              is_active?: any;
              events?: {
                every?: any /* max depth reached */;
                some?: any /* max depth reached */;
                none?: any /* max depth reached */;
              };
              members?: {
                every?: any /* max depth reached */;
                some?: any /* max depth reached */;
                none?: any /* max depth reached */;
              };
              records?: {
                every?: any /* max depth reached */;
                some?: any /* max depth reached */;
                none?: any /* max depth reached */;
              };
            };
            create:
              | any /* circular reference to OrganizationCreateWithoutEventsInput */
              | any /* circular reference to OrganizationUncheckedCreateWithoutEventsInput */;
          };
          connect?: any /* circular reference to OrganizationWhereUniqueInput */;
        };
      }
    | {
        org_event_id?: string;
        organization_id: string;
        event_name: string;
        start_time: Date;
        end_time?: any;
        location?: any;
      };
}

import { z } from "zod";

export const OneOrgEventCreateArgsSchema = z.object({
  data: z.any(),
});
