// Auto-generated by prisma-dto-gen (refactored inline)

export interface ManyOrganizationAndReturnCreateArgs {
  data:
    | {
        organization_id?: string;
        name: string;
        description?: any;
        created_on?: Date;
        updated_on?: any;
        is_active?: any;
      }
    | any /* circular reference to OrganizationCreateManyInput */;
  skipDuplicates?: boolean;
}

import { z } from "zod";

export const ManyOrganizationAndReturnCreateArgsSchema = z.object({
  data: z.any(),
  skipDuplicates: z.boolean().optional(),
});
