// Auto-generated by prisma-dto-gen (refactored inline)

export interface OneNotificationReferenceUpsertArgs {
  where: {
    notification_reference_id?: string;
    AND?:
      | {
          AND?: any /* circular reference to NotificationReferenceWhereInput */;
          OR?: any /* circular reference to NotificationReferenceWhereInput */;
          NOT?: any /* circular reference to NotificationReferenceWhereInput */;
          notification_reference_id?:
            | {
                equals?: any;
                in?: any;
                notIn?: any;
                lt?: any;
                lte?: any;
                gt?: any;
                gte?: any;
                contains?: any;
                startsWith?: any;
                endsWith?: any;
                mode?: any;
                not?:
                  | string
                  | {
                      equals?: any;
                      in?: any;
                      notIn?: any;
                      lt?: any;
                      lte?: any;
                      gt?: any;
                      gte?: any;
                      contains?: any;
                      startsWith?: any;
                      endsWith?: any;
                      not?: string | any /* circular reference to NestedStringFilter */;
                    };
              }
            | string;
          notification_id?: any /* circular reference to StringFilter */ | string;
          referenced_entity_id?: any /* circular reference to StringFilter */ | string;
          status?:
            | {
                equals?: any;
                in?: any;
                notIn?: any;
                not?:
                  | "DRAFT"
                  | "REVIEW"
                  | "PUBLISHED"
                  | "ARCHIVED"
                  | {
                      equals?: any;
                      in?: any;
                      notIn?: any;
                      not?:
                        | "DRAFT"
                        | "REVIEW"
                        | "PUBLISHED"
                        | "ARCHIVED"
                        | any /* circular reference to NestedEnumDocumentStatusFilter */;
                    };
              }
            | "DRAFT"
            | "REVIEW"
            | "PUBLISHED"
            | "ARCHIVED";
          archived?: any;
          notification?:
            | {
                is?: {
                  AND?: any /* circular reference to UserNotificationWhereInput */;
                  OR?: any /* circular reference to UserNotificationWhereInput */;
                  NOT?: any /* circular reference to UserNotificationWhereInput */;
                  notification_id?: any /* circular reference to StringFilter */ | string;
                  recipient_profile_id?: any /* circular reference to StringFilter */ | string;
                  sent_timestamp?:
                    | {
                        equals?: any /* max depth reached */;
                        in?: any /* max depth reached */;
                        notIn?: any /* max depth reached */;
                        lt?: any /* max depth reached */;
                        lte?: any /* max depth reached */;
                        gt?: any /* max depth reached */;
                        gte?: any /* max depth reached */;
                        not?: any /* max depth reached */;
                      }
                    | Date;
                  read_timestamp?: any;
                  message?: any /* circular reference to StringFilter */ | string;
                  notification_refs?: {
                    every?: any /* max depth reached */;
                    some?: any /* max depth reached */;
                    none?: any /* max depth reached */;
                  };
                  user_profile?:
                    | {
                        is?: any /* max depth reached */;
                        isNot?: any /* max depth reached */;
                      }
                    | {
                        AND?: any /* max depth reached */;
                        OR?: any /* max depth reached */;
                        NOT?: any /* max depth reached */;
                        profile_id?: any /* max depth reached */;
                        created_timestamp?: any /* max depth reached */;
                        updated_timestamp?: any /* max depth reached */;
                        deactivated?: any /* max depth reached */;
                        full_name?: any /* max depth reached */;
                        email_address?: any /* max depth reached */;
                        phone_number?: any /* max depth reached */;
                        password_hash?: any /* max depth reached */;
                        account_level?: any /* max depth reached */;
                        created_by_id?: any /* max depth reached */;
                        user_documents?: any /* max depth reached */;
                        user_notifications?: any /* max depth reached */;
                        user_accounts?: any /* max depth reached */;
                        user_two_step_codes?: any /* max depth reached */;
                        user_comments?: any /* max depth reached */;
                        created_by_profile?: any /* max depth reached */;
                        profiles_created?: any /* max depth reached */;
                        threads_as_primary_participant?: any /* max depth reached */;
                        threads_as_secondary_participant?: any /* max depth reached */;
                        sent_messages?: any /* max depth reached */;
                        org_memberships?: any /* max depth reached */;
                        payments?: any /* max depth reached */;
                      };
                };
                isNot?: any /* circular reference to UserNotificationWhereInput */;
              }
            | any /* circular reference to UserNotificationWhereInput */;
        }
      | any /* circular reference to NotificationReferenceWhereInput */;
    OR?: any /* circular reference to NotificationReferenceWhereInput */;
    NOT?: any /* circular reference to NotificationReferenceWhereInput */;
    notification_id?: any /* circular reference to StringFilter */ | string;
    referenced_entity_id?: any /* circular reference to StringFilter */ | string;
    status?:
      | any /* circular reference to EnumDocumentStatusFilter */
      | "DRAFT"
      | "REVIEW"
      | "PUBLISHED"
      | "ARCHIVED";
    archived?: any;
    notification?:
      | any /* circular reference to UserNotificationRelationFilter */
      | any /* circular reference to UserNotificationWhereInput */;
  };
  create:
    | {
        notification_reference_id?: string;
        referenced_entity_id: string;
        status?: "DRAFT" | "REVIEW" | "PUBLISHED" | "ARCHIVED";
        archived?: any;
        notification: {
          create?:
            | {
                notification_id?: string;
                sent_timestamp?: Date;
                read_timestamp?: any;
                message: string;
                user_profile: {
                  create?:
                    | {
                        profile_id?: any /* max depth reached */;
                        created_timestamp?: any /* max depth reached */;
                        updated_timestamp?: any /* max depth reached */;
                        deactivated?: any /* max depth reached */;
                        full_name: any /* max depth reached */;
                        email_address?: any /* max depth reached */;
                        phone_number?: any /* max depth reached */;
                        password_hash?: any /* max depth reached */;
                        account_level?: any /* max depth reached */;
                        user_documents?: any /* max depth reached */;
                        user_accounts?: any /* max depth reached */;
                        user_two_step_codes?: any /* max depth reached */;
                        user_comments?: any /* max depth reached */;
                        created_by_profile?: any /* max depth reached */;
                        profiles_created?: any /* max depth reached */;
                        threads_as_primary_participant?: any /* max depth reached */;
                        threads_as_secondary_participant?: any /* max depth reached */;
                        sent_messages?: any /* max depth reached */;
                        org_memberships?: any /* max depth reached */;
                        payments?: any /* max depth reached */;
                      }
                    | {
                        profile_id?: any /* max depth reached */;
                        created_timestamp?: any /* max depth reached */;
                        updated_timestamp?: any /* max depth reached */;
                        deactivated?: any /* max depth reached */;
                        full_name: any /* max depth reached */;
                        email_address?: any /* max depth reached */;
                        phone_number?: any /* max depth reached */;
                        password_hash?: any /* max depth reached */;
                        account_level?: any /* max depth reached */;
                        created_by_id?: any /* max depth reached */;
                        user_documents?: any /* max depth reached */;
                        user_accounts?: any /* max depth reached */;
                        user_two_step_codes?: any /* max depth reached */;
                        user_comments?: any /* max depth reached */;
                        profiles_created?: any /* max depth reached */;
                        threads_as_primary_participant?: any /* max depth reached */;
                        threads_as_secondary_participant?: any /* max depth reached */;
                        sent_messages?: any /* max depth reached */;
                        org_memberships?: any /* max depth reached */;
                        payments?: any /* max depth reached */;
                      };
                  connectOrCreate?: {
                    where: any /* max depth reached */;
                    create: any /* max depth reached */;
                  };
                  connect?: {
                    profile_id?: any /* max depth reached */;
                    email_address?: any /* max depth reached */;
                    AND?: any /* max depth reached */;
                    OR?: any /* max depth reached */;
                    NOT?: any /* max depth reached */;
                    created_timestamp?: any /* max depth reached */;
                    updated_timestamp?: any /* max depth reached */;
                    deactivated?: any /* max depth reached */;
                    full_name?: any /* max depth reached */;
                    phone_number?: any /* max depth reached */;
                    password_hash?: any /* max depth reached */;
                    account_level?: any /* max depth reached */;
                    created_by_id?: any /* max depth reached */;
                    user_documents?: any /* max depth reached */;
                    user_notifications?: any /* max depth reached */;
                    user_accounts?: any /* max depth reached */;
                    user_two_step_codes?: any /* max depth reached */;
                    user_comments?: any /* max depth reached */;
                    created_by_profile?: any /* max depth reached */;
                    profiles_created?: any /* max depth reached */;
                    threads_as_primary_participant?: any /* max depth reached */;
                    threads_as_secondary_participant?: any /* max depth reached */;
                    sent_messages?: any /* max depth reached */;
                    org_memberships?: any /* max depth reached */;
                    payments?: any /* max depth reached */;
                  };
                };
              }
            | {
                notification_id?: string;
                recipient_profile_id: string;
                sent_timestamp?: Date;
                read_timestamp?: any;
                message: string;
              };
          connectOrCreate?: {
            where: {
              notification_id?: string;
              AND?: any /* circular reference to UserNotificationWhereInput */;
              OR?: any /* circular reference to UserNotificationWhereInput */;
              NOT?: any /* circular reference to UserNotificationWhereInput */;
              recipient_profile_id?: any /* circular reference to StringFilter */ | string;
              sent_timestamp?: any /* circular reference to DateTimeFilter */ | Date;
              read_timestamp?: any;
              message?: any /* circular reference to StringFilter */ | string;
              notification_refs?: any /* circular reference to NotificationReferenceListRelationFilter */;
              user_profile?:
                | any /* circular reference to UserProfileRelationFilter */
                | any /* circular reference to UserProfileWhereInput */;
            };
            create:
              | any /* circular reference to UserNotificationCreateWithoutNotification_refsInput */
              | any /* circular reference to UserNotificationUncheckedCreateWithoutNotification_refsInput */;
          };
          connect?: any /* circular reference to UserNotificationWhereUniqueInput */;
        };
      }
    | {
        notification_reference_id?: string;
        notification_id: string;
        referenced_entity_id: string;
        status?: "DRAFT" | "REVIEW" | "PUBLISHED" | "ARCHIVED";
        archived?: any;
      };
  update:
    | {
        notification_reference_id?:
          | string
          | {
              set?: string;
            };
        referenced_entity_id?:
          | string
          | any /* circular reference to StringFieldUpdateOperationsInput */;
        status?:
          | "DRAFT"
          | "REVIEW"
          | "PUBLISHED"
          | "ARCHIVED"
          | {
              set?: "DRAFT" | "REVIEW" | "PUBLISHED" | "ARCHIVED";
            };
        archived?: any;
        notification?: {
          create?:
            | any /* circular reference to UserNotificationCreateWithoutNotification_refsInput */
            | any /* circular reference to UserNotificationUncheckedCreateWithoutNotification_refsInput */;
          connectOrCreate?: any /* circular reference to UserNotificationCreateOrConnectWithoutNotification_refsInput */;
          upsert?: {
            update:
              | {
                  notification_id?:
                    | string
                    | any /* circular reference to StringFieldUpdateOperationsInput */;
                  sent_timestamp?:
                    | Date
                    | {
                        set?: any /* max depth reached */;
                      };
                  read_timestamp?: any;
                  message?:
                    | string
                    | any /* circular reference to StringFieldUpdateOperationsInput */;
                  user_profile?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                  };
                }
              | {
                  notification_id?:
                    | string
                    | any /* circular reference to StringFieldUpdateOperationsInput */;
                  recipient_profile_id?:
                    | string
                    | any /* circular reference to StringFieldUpdateOperationsInput */;
                  sent_timestamp?:
                    | Date
                    | any /* circular reference to DateTimeFieldUpdateOperationsInput */;
                  read_timestamp?: any;
                  message?:
                    | string
                    | any /* circular reference to StringFieldUpdateOperationsInput */;
                };
            create:
              | any /* circular reference to UserNotificationCreateWithoutNotification_refsInput */
              | any /* circular reference to UserNotificationUncheckedCreateWithoutNotification_refsInput */;
            where?: any /* circular reference to UserNotificationWhereInput */;
          };
          connect?: any /* circular reference to UserNotificationWhereUniqueInput */;
          update?:
            | {
                where?: any /* circular reference to UserNotificationWhereInput */;
                data:
                  | any /* circular reference to UserNotificationUpdateWithoutNotification_refsInput */
                  | any /* circular reference to UserNotificationUncheckedUpdateWithoutNotification_refsInput */;
              }
            | any /* circular reference to UserNotificationUpdateWithoutNotification_refsInput */
            | any /* circular reference to UserNotificationUncheckedUpdateWithoutNotification_refsInput */;
        };
      }
    | {
        notification_reference_id?:
          | string
          | any /* circular reference to StringFieldUpdateOperationsInput */;
        notification_id?: string | any /* circular reference to StringFieldUpdateOperationsInput */;
        referenced_entity_id?:
          | string
          | any /* circular reference to StringFieldUpdateOperationsInput */;
        status?:
          | "DRAFT"
          | "REVIEW"
          | "PUBLISHED"
          | "ARCHIVED"
          | any /* circular reference to EnumDocumentStatusFieldUpdateOperationsInput */;
        archived?: any;
      };
}

import { z } from "zod";

export const OneNotificationReferenceUpsertArgsSchema = z.object({
  where: z.any(),
  create: z.any(),
  update: z.any(),
});
