// Auto-generated by prisma-dto-gen (refactored inline)

export interface ManyOrgRecordCreateArgs {
  data:
    | {
        record_id?: string;
        organization_id: string;
        title: string;
        details?: any;
        created_on?: Date;
        updated_on?: any;
      }
    | any /* circular reference to OrgRecordCreateManyInput */;
  skipDuplicates?: boolean;
}

import { z } from "zod";

export const ManyOrgRecordCreateArgsSchema = z.object({
  data: z.any(),
  skipDuplicates: z.boolean().optional(),
});
