// Auto-generated by prisma-dto-gen (refactored inline)

export interface OneDiscussionThreadUpsertArgs {
  where: {
    thread_id?: string;
    AND?:
      | {
          AND?: any /* circular reference to DiscussionThreadWhereInput */;
          OR?: any /* circular reference to DiscussionThreadWhereInput */;
          NOT?: any /* circular reference to DiscussionThreadWhereInput */;
          thread_id?:
            | {
                equals?: any;
                in?: any;
                notIn?: any;
                lt?: any;
                lte?: any;
                gt?: any;
                gte?: any;
                contains?: any;
                startsWith?: any;
                endsWith?: any;
                mode?: any;
                not?:
                  | string
                  | {
                      equals?: any;
                      in?: any;
                      notIn?: any;
                      lt?: any;
                      lte?: any;
                      gt?: any;
                      gte?: any;
                      contains?: any;
                      startsWith?: any;
                      endsWith?: any;
                      not?: string | any /* circular reference to NestedStringFilter */;
                    };
              }
            | string;
          primary_participant?: any /* circular reference to StringFilter */ | string;
          secondary_participant?: any;
          created_on?:
            | {
                equals?: any;
                in?: any;
                notIn?: any;
                lt?: any;
                lte?: any;
                gt?: any;
                gte?: any;
                not?:
                  | Date
                  | {
                      equals?: any;
                      in?: any;
                      notIn?: any;
                      lt?: any;
                      lte?: any;
                      gt?: any;
                      gte?: any;
                      not?: Date | any /* circular reference to NestedDateTimeFilter */;
                    };
              }
            | Date;
          closed_on?: any;
          is_flagged?: any;
          flagged_reason?: any;
          participant_one?:
            | {
                is?: {
                  AND?: any /* circular reference to UserProfileWhereInput */;
                  OR?: any /* circular reference to UserProfileWhereInput */;
                  NOT?: any /* circular reference to UserProfileWhereInput */;
                  profile_id?: any /* circular reference to StringFilter */ | string;
                  created_timestamp?: any /* circular reference to DateTimeFilter */ | Date;
                  updated_timestamp?: any;
                  deactivated?: any;
                  full_name?: any /* circular reference to StringFilter */ | string;
                  email_address?: any;
                  phone_number?: any;
                  password_hash?: any;
                  account_level?: any;
                  created_by_id?: any;
                  user_documents?: {
                    every?: any /* max depth reached */;
                    some?: any /* max depth reached */;
                    none?: any /* max depth reached */;
                  };
                  user_notifications?: {
                    every?: any /* max depth reached */;
                    some?: any /* max depth reached */;
                    none?: any /* max depth reached */;
                  };
                  user_accounts?: {
                    every?: any /* max depth reached */;
                    some?: any /* max depth reached */;
                    none?: any /* max depth reached */;
                  };
                  user_two_step_codes?: {
                    every?: any /* max depth reached */;
                    some?: any /* max depth reached */;
                    none?: any /* max depth reached */;
                  };
                  user_comments?: {
                    every?: any /* max depth reached */;
                    some?: any /* max depth reached */;
                    none?: any /* max depth reached */;
                  };
                  created_by_profile?: any;
                  profiles_created?: {
                    every?: any /* max depth reached */;
                    some?: any /* max depth reached */;
                    none?: any /* max depth reached */;
                  };
                  threads_as_primary_participant?: {
                    every?: any /* max depth reached */;
                    some?: any /* max depth reached */;
                    none?: any /* max depth reached */;
                  };
                  threads_as_secondary_participant?: any /* circular reference to DiscussionThreadListRelationFilter */;
                  sent_messages?: {
                    every?: any /* max depth reached */;
                    some?: any /* max depth reached */;
                    none?: any /* max depth reached */;
                  };
                  org_memberships?: {
                    every?: any /* max depth reached */;
                    some?: any /* max depth reached */;
                    none?: any /* max depth reached */;
                  };
                  payments?: {
                    every?: any /* max depth reached */;
                    some?: any /* max depth reached */;
                    none?: any /* max depth reached */;
                  };
                };
                isNot?: any /* circular reference to UserProfileWhereInput */;
              }
            | any /* circular reference to UserProfileWhereInput */;
          participant_two?: any;
          messages?: any /* circular reference to ThreadMessageListRelationFilter */;
        }
      | any /* circular reference to DiscussionThreadWhereInput */;
    OR?: any /* circular reference to DiscussionThreadWhereInput */;
    NOT?: any /* circular reference to DiscussionThreadWhereInput */;
    primary_participant?: any /* circular reference to StringFilter */ | string;
    secondary_participant?: any;
    created_on?: any /* circular reference to DateTimeFilter */ | Date;
    closed_on?: any;
    is_flagged?: any;
    flagged_reason?: any;
    participant_one?:
      | any /* circular reference to UserProfileRelationFilter */
      | any /* circular reference to UserProfileWhereInput */;
    participant_two?: any;
    messages?: any /* circular reference to ThreadMessageListRelationFilter */;
  };
  create:
    | {
        thread_id?: string;
        created_on?: Date;
        closed_on?: any;
        is_flagged?: any;
        flagged_reason?: any;
        participant_one: {
          create?:
            | {
                profile_id?: string;
                created_timestamp?: Date;
                updated_timestamp?: any;
                deactivated?: any;
                full_name: string;
                email_address?: any;
                phone_number?: any;
                password_hash?: any;
                account_level?: any;
                user_documents?: {
                  create?:
                    | {
                        document_id?: any /* max depth reached */;
                        title: any /* max depth reached */;
                        content: any /* max depth reached */;
                        status?: any /* max depth reached */;
                        created_at?: any /* max depth reached */;
                        updated_at?: any /* max depth reached */;
                        archived?: any /* max depth reached */;
                        comments?: any /* max depth reached */;
                      }
                    | any /* circular reference to UserDocumentCreateWithoutUser_profileInput */
                    | any /* circular reference to UserDocumentUncheckedCreateWithoutUser_profileInput */;
                  connectOrCreate?:
                    | {
                        where: any /* max depth reached */;
                        create: any /* max depth reached */;
                      }
                    | any /* circular reference to UserDocumentCreateOrConnectWithoutUser_profileInput */;
                  createMany?: {
                    data: any /* max depth reached */;
                    skipDuplicates?: any /* max depth reached */;
                  };
                  connect?:
                    | {
                        document_id?: any /* max depth reached */;
                        AND?: any /* max depth reached */;
                        OR?: any /* max depth reached */;
                        NOT?: any /* max depth reached */;
                        owner_profile_id?: any /* max depth reached */;
                        title?: any /* max depth reached */;
                        content?: any /* max depth reached */;
                        status?: any /* max depth reached */;
                        created_at?: any /* max depth reached */;
                        updated_at?: any /* max depth reached */;
                        archived?: any /* max depth reached */;
                        user_profile?: any /* max depth reached */;
                        comments?: any /* max depth reached */;
                      }
                    | any /* circular reference to UserDocumentWhereUniqueInput */;
                };
                user_notifications?: {
                  create?:
                    | {
                        notification_id?: any /* max depth reached */;
                        sent_timestamp?: any /* max depth reached */;
                        read_timestamp?: any /* max depth reached */;
                        message: any /* max depth reached */;
                        notification_refs?: any /* max depth reached */;
                      }
                    | any /* circular reference to UserNotificationCreateWithoutUser_profileInput */
                    | any /* circular reference to UserNotificationUncheckedCreateWithoutUser_profileInput */;
                  connectOrCreate?:
                    | {
                        where: any /* max depth reached */;
                        create: any /* max depth reached */;
                      }
                    | any /* circular reference to UserNotificationCreateOrConnectWithoutUser_profileInput */;
                  createMany?: {
                    data: any /* max depth reached */;
                    skipDuplicates?: any /* max depth reached */;
                  };
                  connect?:
                    | {
                        notification_id?: any /* max depth reached */;
                        AND?: any /* max depth reached */;
                        OR?: any /* max depth reached */;
                        NOT?: any /* max depth reached */;
                        recipient_profile_id?: any /* max depth reached */;
                        sent_timestamp?: any /* max depth reached */;
                        read_timestamp?: any /* max depth reached */;
                        message?: any /* max depth reached */;
                        notification_refs?: any /* max depth reached */;
                        user_profile?: any /* max depth reached */;
                      }
                    | any /* circular reference to UserNotificationWhereUniqueInput */;
                };
                user_accounts?: {
                  create?:
                    | {
                        account_id?: any /* max depth reached */;
                        name: any /* max depth reached */;
                        created_at?: any /* max depth reached */;
                        modified_at?: any /* max depth reached */;
                        is_active?: any /* max depth reached */;
                      }
                    | any /* circular reference to UserAccountCreateWithoutUser_profileInput */
                    | any /* circular reference to UserAccountUncheckedCreateWithoutUser_profileInput */;
                  connectOrCreate?:
                    | {
                        where: any /* max depth reached */;
                        create: any /* max depth reached */;
                      }
                    | any /* circular reference to UserAccountCreateOrConnectWithoutUser_profileInput */;
                  createMany?: {
                    data: any /* max depth reached */;
                    skipDuplicates?: any /* max depth reached */;
                  };
                  connect?:
                    | {
                        account_id?: any /* max depth reached */;
                        AND?: any /* max depth reached */;
                        OR?: any /* max depth reached */;
                        NOT?: any /* max depth reached */;
                        owner_profile_id?: any /* max depth reached */;
                        name?: any /* max depth reached */;
                        created_at?: any /* max depth reached */;
                        modified_at?: any /* max depth reached */;
                        is_active?: any /* max depth reached */;
                        user_profile?: any /* max depth reached */;
                      }
                    | any /* circular reference to UserAccountWhereUniqueInput */;
                };
                user_two_step_codes?: {
                  create?:
                    | {
                        verification_id?: any /* max depth reached */;
                        code?: any /* max depth reached */;
                        is_verified?: any /* max depth reached */;
                        created_at?: any /* max depth reached */;
                        verification_type: any /* max depth reached */;
                      }
                    | any /* circular reference to TwoStepVerificationCreateWithoutUser_profileInput */
                    | any /* circular reference to TwoStepVerificationUncheckedCreateWithoutUser_profileInput */;
                  connectOrCreate?:
                    | {
                        where: any /* max depth reached */;
                        create: any /* max depth reached */;
                      }
                    | any /* circular reference to TwoStepVerificationCreateOrConnectWithoutUser_profileInput */;
                  createMany?: {
                    data: any /* max depth reached */;
                    skipDuplicates?: any /* max depth reached */;
                  };
                  connect?:
                    | {
                        verification_id?: any /* max depth reached */;
                        AND?: any /* max depth reached */;
                        OR?: any /* max depth reached */;
                        NOT?: any /* max depth reached */;
                        profile_id?: any /* max depth reached */;
                        code?: any /* max depth reached */;
                        is_verified?: any /* max depth reached */;
                        created_at?: any /* max depth reached */;
                        verification_type?: any /* max depth reached */;
                        user_profile?: any /* max depth reached */;
                      }
                    | any /* circular reference to TwoStepVerificationWhereUniqueInput */;
                };
                user_comments?: {
                  create?:
                    | {
                        comment_id?: any /* max depth reached */;
                        text: any /* max depth reached */;
                        created_at?: any /* max depth reached */;
                        edited_at?: any /* max depth reached */;
                        is_deleted?: any /* max depth reached */;
                        user_document: any /* max depth reached */;
                      }
                    | any /* circular reference to UserCommentCreateWithoutUser_profileInput */
                    | {
                        comment_id?: any /* max depth reached */;
                        document_id: any /* max depth reached */;
                        text: any /* max depth reached */;
                        created_at?: any /* max depth reached */;
                        edited_at?: any /* max depth reached */;
                        is_deleted?: any /* max depth reached */;
                      }
                    | any /* circular reference to UserCommentUncheckedCreateWithoutUser_profileInput */;
                  connectOrCreate?:
                    | {
                        where: any /* max depth reached */;
                        create: any /* max depth reached */;
                      }
                    | any /* circular reference to UserCommentCreateOrConnectWithoutUser_profileInput */;
                  createMany?: {
                    data: any /* max depth reached */;
                    skipDuplicates?: any /* max depth reached */;
                  };
                  connect?:
                    | {
                        comment_id?: any /* max depth reached */;
                        AND?: any /* max depth reached */;
                        OR?: any /* max depth reached */;
                        NOT?: any /* max depth reached */;
                        document_id?: any /* max depth reached */;
                        commenter_id?: any /* max depth reached */;
                        text?: any /* max depth reached */;
                        created_at?: any /* max depth reached */;
                        edited_at?: any /* max depth reached */;
                        is_deleted?: any /* max depth reached */;
                        user_document?: any /* max depth reached */;
                        user_profile?: any /* max depth reached */;
                      }
                    | any /* circular reference to UserCommentWhereUniqueInput */;
                };
                created_by_profile?: {
                  create?:
                    | {
                        profile_id?: any /* max depth reached */;
                        created_timestamp?: any /* max depth reached */;
                        updated_timestamp?: any /* max depth reached */;
                        deactivated?: any /* max depth reached */;
                        full_name: any /* max depth reached */;
                        email_address?: any /* max depth reached */;
                        phone_number?: any /* max depth reached */;
                        password_hash?: any /* max depth reached */;
                        account_level?: any /* max depth reached */;
                        user_documents?: any /* max depth reached */;
                        user_notifications?: any /* max depth reached */;
                        user_accounts?: any /* max depth reached */;
                        user_two_step_codes?: any /* max depth reached */;
                        user_comments?: any /* max depth reached */;
                        created_by_profile?: any /* max depth reached */;
                        threads_as_primary_participant?: any /* max depth reached */;
                        threads_as_secondary_participant?: any /* max depth reached */;
                        sent_messages?: any /* max depth reached */;
                        org_memberships?: any /* max depth reached */;
                        payments?: any /* max depth reached */;
                      }
                    | {
                        profile_id?: any /* max depth reached */;
                        created_timestamp?: any /* max depth reached */;
                        updated_timestamp?: any /* max depth reached */;
                        deactivated?: any /* max depth reached */;
                        full_name: any /* max depth reached */;
                        email_address?: any /* max depth reached */;
                        phone_number?: any /* max depth reached */;
                        password_hash?: any /* max depth reached */;
                        account_level?: any /* max depth reached */;
                        created_by_id?: any /* max depth reached */;
                        user_documents?: any /* max depth reached */;
                        user_notifications?: any /* max depth reached */;
                        user_accounts?: any /* max depth reached */;
                        user_two_step_codes?: any /* max depth reached */;
                        user_comments?: any /* max depth reached */;
                        threads_as_primary_participant?: any /* max depth reached */;
                        threads_as_secondary_participant?: any /* max depth reached */;
                        sent_messages?: any /* max depth reached */;
                        org_memberships?: any /* max depth reached */;
                        payments?: any /* max depth reached */;
                      };
                  connectOrCreate?: {
                    where: any /* max depth reached */;
                    create: any /* max depth reached */;
                  };
                  connect?: {
                    profile_id?: any /* max depth reached */;
                    email_address?: any /* max depth reached */;
                    AND?: any /* max depth reached */;
                    OR?: any /* max depth reached */;
                    NOT?: any /* max depth reached */;
                    created_timestamp?: any /* max depth reached */;
                    updated_timestamp?: any /* max depth reached */;
                    deactivated?: any /* max depth reached */;
                    full_name?: any /* max depth reached */;
                    phone_number?: any /* max depth reached */;
                    password_hash?: any /* max depth reached */;
                    account_level?: any /* max depth reached */;
                    created_by_id?: any /* max depth reached */;
                    user_documents?: any /* max depth reached */;
                    user_notifications?: any /* max depth reached */;
                    user_accounts?: any /* max depth reached */;
                    user_two_step_codes?: any /* max depth reached */;
                    user_comments?: any /* max depth reached */;
                    created_by_profile?: any /* max depth reached */;
                    profiles_created?: any /* max depth reached */;
                    threads_as_primary_participant?: any /* max depth reached */;
                    threads_as_secondary_participant?: any /* max depth reached */;
                    sent_messages?: any /* max depth reached */;
                    org_memberships?: any /* max depth reached */;
                    payments?: any /* max depth reached */;
                  };
                };
                profiles_created?: {
                  create?:
                    | {
                        profile_id?: any /* max depth reached */;
                        created_timestamp?: any /* max depth reached */;
                        updated_timestamp?: any /* max depth reached */;
                        deactivated?: any /* max depth reached */;
                        full_name: any /* max depth reached */;
                        email_address?: any /* max depth reached */;
                        phone_number?: any /* max depth reached */;
                        password_hash?: any /* max depth reached */;
                        account_level?: any /* max depth reached */;
                        user_documents?: any /* max depth reached */;
                        user_notifications?: any /* max depth reached */;
                        user_accounts?: any /* max depth reached */;
                        user_two_step_codes?: any /* max depth reached */;
                        user_comments?: any /* max depth reached */;
                        profiles_created?: any /* max depth reached */;
                        threads_as_primary_participant?: any /* max depth reached */;
                        threads_as_secondary_participant?: any /* max depth reached */;
                        sent_messages?: any /* max depth reached */;
                        org_memberships?: any /* max depth reached */;
                        payments?: any /* max depth reached */;
                      }
                    | any /* circular reference to UserProfileCreateWithoutCreated_by_profileInput */
                    | any /* circular reference to UserProfileUncheckedCreateWithoutCreated_by_profileInput */;
                  connectOrCreate?:
                    | {
                        where: any /* max depth reached */;
                        create: any /* max depth reached */;
                      }
                    | any /* circular reference to UserProfileCreateOrConnectWithoutCreated_by_profileInput */;
                  createMany?: {
                    data: any /* max depth reached */;
                    skipDuplicates?: any /* max depth reached */;
                  };
                  connect?: any /* circular reference to UserProfileWhereUniqueInput */;
                };
                threads_as_secondary_participant?: {
                  create?:
                    | {
                        thread_id?: any /* max depth reached */;
                        created_on?: any /* max depth reached */;
                        closed_on?: any /* max depth reached */;
                        is_flagged?: any /* max depth reached */;
                        flagged_reason?: any /* max depth reached */;
                        participant_one: any /* max depth reached */;
                        messages?: any /* max depth reached */;
                      }
                    | any /* circular reference to DiscussionThreadCreateWithoutParticipant_twoInput */
                    | {
                        thread_id?: any /* max depth reached */;
                        primary_participant: any /* max depth reached */;
                        created_on?: any /* max depth reached */;
                        closed_on?: any /* max depth reached */;
                        is_flagged?: any /* max depth reached */;
                        flagged_reason?: any /* max depth reached */;
                        messages?: any /* max depth reached */;
                      }
                    | any /* circular reference to DiscussionThreadUncheckedCreateWithoutParticipant_twoInput */;
                  connectOrCreate?:
                    | {
                        where: any /* max depth reached */;
                        create: any /* max depth reached */;
                      }
                    | any /* circular reference to DiscussionThreadCreateOrConnectWithoutParticipant_twoInput */;
                  createMany?: {
                    data: any /* max depth reached */;
                    skipDuplicates?: any /* max depth reached */;
                  };
                  connect?: any /* circular reference to DiscussionThreadWhereUniqueInput */;
                };
                sent_messages?: {
                  create?:
                    | {
                        message_id?: any /* max depth reached */;
                        content: any /* max depth reached */;
                        sent_at?: any /* max depth reached */;
                        updated_at?: any /* max depth reached */;
                        is_archived?: any /* max depth reached */;
                        discussion_thread: any /* max depth reached */;
                      }
                    | any /* circular reference to ThreadMessageCreateWithoutSenderInput */
                    | {
                        message_id?: any /* max depth reached */;
                        thread_id: any /* max depth reached */;
                        content: any /* max depth reached */;
                        sent_at?: any /* max depth reached */;
                        updated_at?: any /* max depth reached */;
                        is_archived?: any /* max depth reached */;
                      }
                    | any /* circular reference to ThreadMessageUncheckedCreateWithoutSenderInput */;
                  connectOrCreate?:
                    | {
                        where: any /* max depth reached */;
                        create: any /* max depth reached */;
                      }
                    | any /* circular reference to ThreadMessageCreateOrConnectWithoutSenderInput */;
                  createMany?: {
                    data: any /* max depth reached */;
                    skipDuplicates?: any /* max depth reached */;
                  };
                  connect?:
                    | {
                        message_id?: any /* max depth reached */;
                        AND?: any /* max depth reached */;
                        OR?: any /* max depth reached */;
                        NOT?: any /* max depth reached */;
                        thread_id?: any /* max depth reached */;
                        sender_id?: any /* max depth reached */;
                        content?: any /* max depth reached */;
                        sent_at?: any /* max depth reached */;
                        updated_at?: any /* max depth reached */;
                        is_archived?: any /* max depth reached */;
                        discussion_thread?: any /* max depth reached */;
                        sender?: any /* max depth reached */;
                      }
                    | any /* circular reference to ThreadMessageWhereUniqueInput */;
                };
                org_memberships?: {
                  create?:
                    | {
                        membership_id?: any /* max depth reached */;
                        joined_on?: any /* max depth reached */;
                        is_active?: any /* max depth reached */;
                        organization: any /* max depth reached */;
                      }
                    | any /* circular reference to OrgMembershipCreateWithoutUser_profileInput */
                    | {
                        membership_id?: any /* max depth reached */;
                        organization_id: any /* max depth reached */;
                        joined_on?: any /* max depth reached */;
                        is_active?: any /* max depth reached */;
                      }
                    | any /* circular reference to OrgMembershipUncheckedCreateWithoutUser_profileInput */;
                  connectOrCreate?:
                    | {
                        where: any /* max depth reached */;
                        create: any /* max depth reached */;
                      }
                    | any /* circular reference to OrgMembershipCreateOrConnectWithoutUser_profileInput */;
                  createMany?: {
                    data: any /* max depth reached */;
                    skipDuplicates?: any /* max depth reached */;
                  };
                  connect?:
                    | {
                        membership_id?: any /* max depth reached */;
                        AND?: any /* max depth reached */;
                        OR?: any /* max depth reached */;
                        NOT?: any /* max depth reached */;
                        organization_id?: any /* max depth reached */;
                        profile_id?: any /* max depth reached */;
                        joined_on?: any /* max depth reached */;
                        is_active?: any /* max depth reached */;
                        organization?: any /* max depth reached */;
                        user_profile?: any /* max depth reached */;
                      }
                    | any /* circular reference to OrgMembershipWhereUniqueInput */;
                };
                payments?: {
                  create?:
                    | {
                        payment_id?: any /* max depth reached */;
                        amount: any /* max depth reached */;
                        paid_at?: any /* max depth reached */;
                        status?: any /* max depth reached */;
                        reference_note?: any /* max depth reached */;
                      }
                    | any /* circular reference to PaymentCreateWithoutPayerInput */
                    | any /* circular reference to PaymentUncheckedCreateWithoutPayerInput */;
                  connectOrCreate?:
                    | {
                        where: any /* max depth reached */;
                        create: any /* max depth reached */;
                      }
                    | any /* circular reference to PaymentCreateOrConnectWithoutPayerInput */;
                  createMany?: {
                    data: any /* max depth reached */;
                    skipDuplicates?: any /* max depth reached */;
                  };
                  connect?:
                    | {
                        payment_id?: any /* max depth reached */;
                        AND?: any /* max depth reached */;
                        OR?: any /* max depth reached */;
                        NOT?: any /* max depth reached */;
                        payer_id?: any /* max depth reached */;
                        amount?: any /* max depth reached */;
                        paid_at?: any /* max depth reached */;
                        status?: any /* max depth reached */;
                        reference_note?: any /* max depth reached */;
                        payer?: any /* max depth reached */;
                      }
                    | any /* circular reference to PaymentWhereUniqueInput */;
                };
              }
            | {
                profile_id?: string;
                created_timestamp?: Date;
                updated_timestamp?: any;
                deactivated?: any;
                full_name: string;
                email_address?: any;
                phone_number?: any;
                password_hash?: any;
                account_level?: any;
                created_by_id?: any;
                user_documents?: {
                  create?:
                    | any /* circular reference to UserDocumentCreateWithoutUser_profileInput */
                    | any /* circular reference to UserDocumentUncheckedCreateWithoutUser_profileInput */;
                  connectOrCreate?: any /* circular reference to UserDocumentCreateOrConnectWithoutUser_profileInput */;
                  createMany?: any /* circular reference to UserDocumentCreateManyUser_profileInputEnvelope */;
                  connect?: any /* circular reference to UserDocumentWhereUniqueInput */;
                };
                user_notifications?: {
                  create?:
                    | any /* circular reference to UserNotificationCreateWithoutUser_profileInput */
                    | any /* circular reference to UserNotificationUncheckedCreateWithoutUser_profileInput */;
                  connectOrCreate?: any /* circular reference to UserNotificationCreateOrConnectWithoutUser_profileInput */;
                  createMany?: any /* circular reference to UserNotificationCreateManyUser_profileInputEnvelope */;
                  connect?: any /* circular reference to UserNotificationWhereUniqueInput */;
                };
                user_accounts?: {
                  create?:
                    | any /* circular reference to UserAccountCreateWithoutUser_profileInput */
                    | any /* circular reference to UserAccountUncheckedCreateWithoutUser_profileInput */;
                  connectOrCreate?: any /* circular reference to UserAccountCreateOrConnectWithoutUser_profileInput */;
                  createMany?: any /* circular reference to UserAccountCreateManyUser_profileInputEnvelope */;
                  connect?: any /* circular reference to UserAccountWhereUniqueInput */;
                };
                user_two_step_codes?: {
                  create?:
                    | any /* circular reference to TwoStepVerificationCreateWithoutUser_profileInput */
                    | any /* circular reference to TwoStepVerificationUncheckedCreateWithoutUser_profileInput */;
                  connectOrCreate?: any /* circular reference to TwoStepVerificationCreateOrConnectWithoutUser_profileInput */;
                  createMany?: any /* circular reference to TwoStepVerificationCreateManyUser_profileInputEnvelope */;
                  connect?: any /* circular reference to TwoStepVerificationWhereUniqueInput */;
                };
                user_comments?: {
                  create?:
                    | any /* circular reference to UserCommentCreateWithoutUser_profileInput */
                    | any /* circular reference to UserCommentUncheckedCreateWithoutUser_profileInput */;
                  connectOrCreate?: any /* circular reference to UserCommentCreateOrConnectWithoutUser_profileInput */;
                  createMany?: any /* circular reference to UserCommentCreateManyUser_profileInputEnvelope */;
                  connect?: any /* circular reference to UserCommentWhereUniqueInput */;
                };
                profiles_created?: {
                  create?:
                    | any /* circular reference to UserProfileCreateWithoutCreated_by_profileInput */
                    | any /* circular reference to UserProfileUncheckedCreateWithoutCreated_by_profileInput */;
                  connectOrCreate?: any /* circular reference to UserProfileCreateOrConnectWithoutCreated_by_profileInput */;
                  createMany?: any /* circular reference to UserProfileCreateManyCreated_by_profileInputEnvelope */;
                  connect?: any /* circular reference to UserProfileWhereUniqueInput */;
                };
                threads_as_secondary_participant?: {
                  create?:
                    | any /* circular reference to DiscussionThreadCreateWithoutParticipant_twoInput */
                    | any /* circular reference to DiscussionThreadUncheckedCreateWithoutParticipant_twoInput */;
                  connectOrCreate?: any /* circular reference to DiscussionThreadCreateOrConnectWithoutParticipant_twoInput */;
                  createMany?: any /* circular reference to DiscussionThreadCreateManyParticipant_twoInputEnvelope */;
                  connect?: any /* circular reference to DiscussionThreadWhereUniqueInput */;
                };
                sent_messages?: {
                  create?:
                    | any /* circular reference to ThreadMessageCreateWithoutSenderInput */
                    | any /* circular reference to ThreadMessageUncheckedCreateWithoutSenderInput */;
                  connectOrCreate?: any /* circular reference to ThreadMessageCreateOrConnectWithoutSenderInput */;
                  createMany?: any /* circular reference to ThreadMessageCreateManySenderInputEnvelope */;
                  connect?: any /* circular reference to ThreadMessageWhereUniqueInput */;
                };
                org_memberships?: {
                  create?:
                    | any /* circular reference to OrgMembershipCreateWithoutUser_profileInput */
                    | any /* circular reference to OrgMembershipUncheckedCreateWithoutUser_profileInput */;
                  connectOrCreate?: any /* circular reference to OrgMembershipCreateOrConnectWithoutUser_profileInput */;
                  createMany?: any /* circular reference to OrgMembershipCreateManyUser_profileInputEnvelope */;
                  connect?: any /* circular reference to OrgMembershipWhereUniqueInput */;
                };
                payments?: {
                  create?:
                    | any /* circular reference to PaymentCreateWithoutPayerInput */
                    | any /* circular reference to PaymentUncheckedCreateWithoutPayerInput */;
                  connectOrCreate?: any /* circular reference to PaymentCreateOrConnectWithoutPayerInput */;
                  createMany?: any /* circular reference to PaymentCreateManyPayerInputEnvelope */;
                  connect?: any /* circular reference to PaymentWhereUniqueInput */;
                };
              };
          connectOrCreate?: {
            where: any /* circular reference to UserProfileWhereUniqueInput */;
            create:
              | any /* circular reference to UserProfileCreateWithoutThreads_as_primary_participantInput */
              | any /* circular reference to UserProfileUncheckedCreateWithoutThreads_as_primary_participantInput */;
          };
          connect?: any /* circular reference to UserProfileWhereUniqueInput */;
        };
        participant_two?: {
          create?:
            | {
                profile_id?: string;
                created_timestamp?: Date;
                updated_timestamp?: any;
                deactivated?: any;
                full_name: string;
                email_address?: any;
                phone_number?: any;
                password_hash?: any;
                account_level?: any;
                user_documents?: any /* circular reference to UserDocumentCreateNestedManyWithoutUser_profileInput */;
                user_notifications?: any /* circular reference to UserNotificationCreateNestedManyWithoutUser_profileInput */;
                user_accounts?: any /* circular reference to UserAccountCreateNestedManyWithoutUser_profileInput */;
                user_two_step_codes?: any /* circular reference to TwoStepVerificationCreateNestedManyWithoutUser_profileInput */;
                user_comments?: any /* circular reference to UserCommentCreateNestedManyWithoutUser_profileInput */;
                created_by_profile?: any /* circular reference to UserProfileCreateNestedOneWithoutProfiles_createdInput */;
                profiles_created?: any /* circular reference to UserProfileCreateNestedManyWithoutCreated_by_profileInput */;
                threads_as_primary_participant?: {
                  create?:
                    | {
                        thread_id?: any /* max depth reached */;
                        created_on?: any /* max depth reached */;
                        closed_on?: any /* max depth reached */;
                        is_flagged?: any /* max depth reached */;
                        flagged_reason?: any /* max depth reached */;
                        participant_two?: any /* max depth reached */;
                        messages?: any /* max depth reached */;
                      }
                    | any /* circular reference to DiscussionThreadCreateWithoutParticipant_oneInput */
                    | {
                        thread_id?: any /* max depth reached */;
                        secondary_participant?: any /* max depth reached */;
                        created_on?: any /* max depth reached */;
                        closed_on?: any /* max depth reached */;
                        is_flagged?: any /* max depth reached */;
                        flagged_reason?: any /* max depth reached */;
                        messages?: any /* max depth reached */;
                      }
                    | any /* circular reference to DiscussionThreadUncheckedCreateWithoutParticipant_oneInput */;
                  connectOrCreate?:
                    | {
                        where: any /* max depth reached */;
                        create: any /* max depth reached */;
                      }
                    | any /* circular reference to DiscussionThreadCreateOrConnectWithoutParticipant_oneInput */;
                  createMany?: {
                    data: any /* max depth reached */;
                    skipDuplicates?: any /* max depth reached */;
                  };
                  connect?: any /* circular reference to DiscussionThreadWhereUniqueInput */;
                };
                sent_messages?: any /* circular reference to ThreadMessageCreateNestedManyWithoutSenderInput */;
                org_memberships?: any /* circular reference to OrgMembershipCreateNestedManyWithoutUser_profileInput */;
                payments?: any /* circular reference to PaymentCreateNestedManyWithoutPayerInput */;
              }
            | {
                profile_id?: string;
                created_timestamp?: Date;
                updated_timestamp?: any;
                deactivated?: any;
                full_name: string;
                email_address?: any;
                phone_number?: any;
                password_hash?: any;
                account_level?: any;
                created_by_id?: any;
                user_documents?: any /* circular reference to UserDocumentUncheckedCreateNestedManyWithoutUser_profileInput */;
                user_notifications?: any /* circular reference to UserNotificationUncheckedCreateNestedManyWithoutUser_profileInput */;
                user_accounts?: any /* circular reference to UserAccountUncheckedCreateNestedManyWithoutUser_profileInput */;
                user_two_step_codes?: any /* circular reference to TwoStepVerificationUncheckedCreateNestedManyWithoutUser_profileInput */;
                user_comments?: any /* circular reference to UserCommentUncheckedCreateNestedManyWithoutUser_profileInput */;
                profiles_created?: any /* circular reference to UserProfileUncheckedCreateNestedManyWithoutCreated_by_profileInput */;
                threads_as_primary_participant?: {
                  create?:
                    | any /* circular reference to DiscussionThreadCreateWithoutParticipant_oneInput */
                    | any /* circular reference to DiscussionThreadUncheckedCreateWithoutParticipant_oneInput */;
                  connectOrCreate?: any /* circular reference to DiscussionThreadCreateOrConnectWithoutParticipant_oneInput */;
                  createMany?: any /* circular reference to DiscussionThreadCreateManyParticipant_oneInputEnvelope */;
                  connect?: any /* circular reference to DiscussionThreadWhereUniqueInput */;
                };
                sent_messages?: any /* circular reference to ThreadMessageUncheckedCreateNestedManyWithoutSenderInput */;
                org_memberships?: any /* circular reference to OrgMembershipUncheckedCreateNestedManyWithoutUser_profileInput */;
                payments?: any /* circular reference to PaymentUncheckedCreateNestedManyWithoutPayerInput */;
              };
          connectOrCreate?: {
            where: any /* circular reference to UserProfileWhereUniqueInput */;
            create:
              | any /* circular reference to UserProfileCreateWithoutThreads_as_secondary_participantInput */
              | any /* circular reference to UserProfileUncheckedCreateWithoutThreads_as_secondary_participantInput */;
          };
          connect?: any /* circular reference to UserProfileWhereUniqueInput */;
        };
        messages?: {
          create?:
            | {
                message_id?: string;
                content: string;
                sent_at?: Date;
                updated_at?: any;
                is_archived?: any;
                sender: {
                  create?:
                    | {
                        profile_id?: any /* max depth reached */;
                        created_timestamp?: any /* max depth reached */;
                        updated_timestamp?: any /* max depth reached */;
                        deactivated?: any /* max depth reached */;
                        full_name: any /* max depth reached */;
                        email_address?: any /* max depth reached */;
                        phone_number?: any /* max depth reached */;
                        password_hash?: any /* max depth reached */;
                        account_level?: any /* max depth reached */;
                        user_documents?: any /* max depth reached */;
                        user_notifications?: any /* max depth reached */;
                        user_accounts?: any /* max depth reached */;
                        user_two_step_codes?: any /* max depth reached */;
                        user_comments?: any /* max depth reached */;
                        created_by_profile?: any /* max depth reached */;
                        profiles_created?: any /* max depth reached */;
                        threads_as_primary_participant?: any /* max depth reached */;
                        threads_as_secondary_participant?: any /* max depth reached */;
                        org_memberships?: any /* max depth reached */;
                        payments?: any /* max depth reached */;
                      }
                    | {
                        profile_id?: any /* max depth reached */;
                        created_timestamp?: any /* max depth reached */;
                        updated_timestamp?: any /* max depth reached */;
                        deactivated?: any /* max depth reached */;
                        full_name: any /* max depth reached */;
                        email_address?: any /* max depth reached */;
                        phone_number?: any /* max depth reached */;
                        password_hash?: any /* max depth reached */;
                        account_level?: any /* max depth reached */;
                        created_by_id?: any /* max depth reached */;
                        user_documents?: any /* max depth reached */;
                        user_notifications?: any /* max depth reached */;
                        user_accounts?: any /* max depth reached */;
                        user_two_step_codes?: any /* max depth reached */;
                        user_comments?: any /* max depth reached */;
                        profiles_created?: any /* max depth reached */;
                        threads_as_primary_participant?: any /* max depth reached */;
                        threads_as_secondary_participant?: any /* max depth reached */;
                        org_memberships?: any /* max depth reached */;
                        payments?: any /* max depth reached */;
                      };
                  connectOrCreate?: {
                    where: any /* max depth reached */;
                    create: any /* max depth reached */;
                  };
                  connect?: any /* circular reference to UserProfileWhereUniqueInput */;
                };
              }
            | any /* circular reference to ThreadMessageCreateWithoutDiscussion_threadInput */
            | {
                message_id?: string;
                sender_id: string;
                content: string;
                sent_at?: Date;
                updated_at?: any;
                is_archived?: any;
              }
            | any /* circular reference to ThreadMessageUncheckedCreateWithoutDiscussion_threadInput */;
          connectOrCreate?:
            | {
                where: any /* circular reference to ThreadMessageWhereUniqueInput */;
                create:
                  | any /* circular reference to ThreadMessageCreateWithoutDiscussion_threadInput */
                  | any /* circular reference to ThreadMessageUncheckedCreateWithoutDiscussion_threadInput */;
              }
            | any /* circular reference to ThreadMessageCreateOrConnectWithoutDiscussion_threadInput */;
          createMany?: {
            data:
              | {
                  message_id?: string;
                  sender_id: string;
                  content: string;
                  sent_at?: Date;
                  updated_at?: any;
                  is_archived?: any;
                }
              | any /* circular reference to ThreadMessageCreateManyDiscussion_threadInput */;
            skipDuplicates?: boolean;
          };
          connect?: any /* circular reference to ThreadMessageWhereUniqueInput */;
        };
      }
    | {
        thread_id?: string;
        primary_participant: string;
        secondary_participant?: any;
        created_on?: Date;
        closed_on?: any;
        is_flagged?: any;
        flagged_reason?: any;
        messages?: {
          create?:
            | any /* circular reference to ThreadMessageCreateWithoutDiscussion_threadInput */
            | any /* circular reference to ThreadMessageUncheckedCreateWithoutDiscussion_threadInput */;
          connectOrCreate?: any /* circular reference to ThreadMessageCreateOrConnectWithoutDiscussion_threadInput */;
          createMany?: any /* circular reference to ThreadMessageCreateManyDiscussion_threadInputEnvelope */;
          connect?: any /* circular reference to ThreadMessageWhereUniqueInput */;
        };
      };
  update:
    | {
        thread_id?:
          | string
          | {
              set?: string;
            };
        created_on?:
          | Date
          | {
              set?: Date;
            };
        closed_on?: any;
        is_flagged?: any;
        flagged_reason?: any;
        participant_one?: {
          create?:
            | any /* circular reference to UserProfileCreateWithoutThreads_as_primary_participantInput */
            | any /* circular reference to UserProfileUncheckedCreateWithoutThreads_as_primary_participantInput */;
          connectOrCreate?: any /* circular reference to UserProfileCreateOrConnectWithoutThreads_as_primary_participantInput */;
          upsert?: {
            update:
              | {
                  profile_id?:
                    | string
                    | any /* circular reference to StringFieldUpdateOperationsInput */;
                  created_timestamp?:
                    | Date
                    | any /* circular reference to DateTimeFieldUpdateOperationsInput */;
                  updated_timestamp?: any;
                  deactivated?: any;
                  full_name?:
                    | string
                    | any /* circular reference to StringFieldUpdateOperationsInput */;
                  email_address?: any;
                  phone_number?: any;
                  password_hash?: any;
                  account_level?: any;
                  user_documents?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  user_notifications?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  user_accounts?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  user_two_step_codes?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  user_comments?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  created_by_profile?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                  };
                  profiles_created?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  threads_as_secondary_participant?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  sent_messages?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  org_memberships?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  payments?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                }
              | {
                  profile_id?:
                    | string
                    | any /* circular reference to StringFieldUpdateOperationsInput */;
                  created_timestamp?:
                    | Date
                    | any /* circular reference to DateTimeFieldUpdateOperationsInput */;
                  updated_timestamp?: any;
                  deactivated?: any;
                  full_name?:
                    | string
                    | any /* circular reference to StringFieldUpdateOperationsInput */;
                  email_address?: any;
                  phone_number?: any;
                  password_hash?: any;
                  account_level?: any;
                  created_by_id?: any;
                  user_documents?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  user_notifications?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  user_accounts?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  user_two_step_codes?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  user_comments?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  profiles_created?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  threads_as_secondary_participant?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  sent_messages?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  org_memberships?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  payments?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                };
            create:
              | any /* circular reference to UserProfileCreateWithoutThreads_as_primary_participantInput */
              | any /* circular reference to UserProfileUncheckedCreateWithoutThreads_as_primary_participantInput */;
            where?: any /* circular reference to UserProfileWhereInput */;
          };
          connect?: any /* circular reference to UserProfileWhereUniqueInput */;
          update?:
            | {
                where?: any /* circular reference to UserProfileWhereInput */;
                data:
                  | any /* circular reference to UserProfileUpdateWithoutThreads_as_primary_participantInput */
                  | any /* circular reference to UserProfileUncheckedUpdateWithoutThreads_as_primary_participantInput */;
              }
            | any /* circular reference to UserProfileUpdateWithoutThreads_as_primary_participantInput */
            | any /* circular reference to UserProfileUncheckedUpdateWithoutThreads_as_primary_participantInput */;
        };
        participant_two?: {
          create?:
            | any /* circular reference to UserProfileCreateWithoutThreads_as_secondary_participantInput */
            | any /* circular reference to UserProfileUncheckedCreateWithoutThreads_as_secondary_participantInput */;
          connectOrCreate?: any /* circular reference to UserProfileCreateOrConnectWithoutThreads_as_secondary_participantInput */;
          upsert?: {
            update:
              | {
                  profile_id?:
                    | string
                    | any /* circular reference to StringFieldUpdateOperationsInput */;
                  created_timestamp?:
                    | Date
                    | any /* circular reference to DateTimeFieldUpdateOperationsInput */;
                  updated_timestamp?: any;
                  deactivated?: any;
                  full_name?:
                    | string
                    | any /* circular reference to StringFieldUpdateOperationsInput */;
                  email_address?: any;
                  phone_number?: any;
                  password_hash?: any;
                  account_level?: any;
                  user_documents?: any /* circular reference to UserDocumentUpdateManyWithoutUser_profileNestedInput */;
                  user_notifications?: any /* circular reference to UserNotificationUpdateManyWithoutUser_profileNestedInput */;
                  user_accounts?: any /* circular reference to UserAccountUpdateManyWithoutUser_profileNestedInput */;
                  user_two_step_codes?: any /* circular reference to TwoStepVerificationUpdateManyWithoutUser_profileNestedInput */;
                  user_comments?: any /* circular reference to UserCommentUpdateManyWithoutUser_profileNestedInput */;
                  created_by_profile?: any /* circular reference to UserProfileUpdateOneWithoutProfiles_createdNestedInput */;
                  profiles_created?: any /* circular reference to UserProfileUpdateManyWithoutCreated_by_profileNestedInput */;
                  threads_as_primary_participant?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  sent_messages?: any /* circular reference to ThreadMessageUpdateManyWithoutSenderNestedInput */;
                  org_memberships?: any /* circular reference to OrgMembershipUpdateManyWithoutUser_profileNestedInput */;
                  payments?: any /* circular reference to PaymentUpdateManyWithoutPayerNestedInput */;
                }
              | {
                  profile_id?:
                    | string
                    | any /* circular reference to StringFieldUpdateOperationsInput */;
                  created_timestamp?:
                    | Date
                    | any /* circular reference to DateTimeFieldUpdateOperationsInput */;
                  updated_timestamp?: any;
                  deactivated?: any;
                  full_name?:
                    | string
                    | any /* circular reference to StringFieldUpdateOperationsInput */;
                  email_address?: any;
                  phone_number?: any;
                  password_hash?: any;
                  account_level?: any;
                  created_by_id?: any;
                  user_documents?: any /* circular reference to UserDocumentUncheckedUpdateManyWithoutUser_profileNestedInput */;
                  user_notifications?: any /* circular reference to UserNotificationUncheckedUpdateManyWithoutUser_profileNestedInput */;
                  user_accounts?: any /* circular reference to UserAccountUncheckedUpdateManyWithoutUser_profileNestedInput */;
                  user_two_step_codes?: any /* circular reference to TwoStepVerificationUncheckedUpdateManyWithoutUser_profileNestedInput */;
                  user_comments?: any /* circular reference to UserCommentUncheckedUpdateManyWithoutUser_profileNestedInput */;
                  profiles_created?: any /* circular reference to UserProfileUncheckedUpdateManyWithoutCreated_by_profileNestedInput */;
                  threads_as_primary_participant?: {
                    create?: any /* max depth reached */;
                    connectOrCreate?: any /* max depth reached */;
                    upsert?: any /* max depth reached */;
                    createMany?: any /* max depth reached */;
                    set?: any /* max depth reached */;
                    disconnect?: any /* max depth reached */;
                    delete?: any /* max depth reached */;
                    connect?: any /* max depth reached */;
                    update?: any /* max depth reached */;
                    updateMany?: any /* max depth reached */;
                    deleteMany?: any /* max depth reached */;
                  };
                  sent_messages?: any /* circular reference to ThreadMessageUncheckedUpdateManyWithoutSenderNestedInput */;
                  org_memberships?: any /* circular reference to OrgMembershipUncheckedUpdateManyWithoutUser_profileNestedInput */;
                  payments?: any /* circular reference to PaymentUncheckedUpdateManyWithoutPayerNestedInput */;
                };
            create:
              | any /* circular reference to UserProfileCreateWithoutThreads_as_secondary_participantInput */
              | any /* circular reference to UserProfileUncheckedCreateWithoutThreads_as_secondary_participantInput */;
            where?: any /* circular reference to UserProfileWhereInput */;
          };
          disconnect?: boolean | any /* circular reference to UserProfileWhereInput */;
          delete?: boolean | any /* circular reference to UserProfileWhereInput */;
          connect?: any /* circular reference to UserProfileWhereUniqueInput */;
          update?:
            | {
                where?: any /* circular reference to UserProfileWhereInput */;
                data:
                  | any /* circular reference to UserProfileUpdateWithoutThreads_as_secondary_participantInput */
                  | any /* circular reference to UserProfileUncheckedUpdateWithoutThreads_as_secondary_participantInput */;
              }
            | any /* circular reference to UserProfileUpdateWithoutThreads_as_secondary_participantInput */
            | any /* circular reference to UserProfileUncheckedUpdateWithoutThreads_as_secondary_participantInput */;
        };
        messages?: {
          create?:
            | any /* circular reference to ThreadMessageCreateWithoutDiscussion_threadInput */
            | any /* circular reference to ThreadMessageUncheckedCreateWithoutDiscussion_threadInput */;
          connectOrCreate?: any /* circular reference to ThreadMessageCreateOrConnectWithoutDiscussion_threadInput */;
          upsert?:
            | {
                where: any /* circular reference to ThreadMessageWhereUniqueInput */;
                update:
                  | {
                      message_id?:
                        | string
                        | any /* circular reference to StringFieldUpdateOperationsInput */;
                      content?:
                        | string
                        | any /* circular reference to StringFieldUpdateOperationsInput */;
                      sent_at?:
                        | Date
                        | any /* circular reference to DateTimeFieldUpdateOperationsInput */;
                      updated_at?: any;
                      is_archived?: any;
                      sender?: {
                        create?: any /* max depth reached */;
                        connectOrCreate?: any /* max depth reached */;
                        upsert?: any /* max depth reached */;
                        connect?: any /* max depth reached */;
                        update?: any /* max depth reached */;
                      };
                    }
                  | {
                      message_id?:
                        | string
                        | any /* circular reference to StringFieldUpdateOperationsInput */;
                      sender_id?:
                        | string
                        | any /* circular reference to StringFieldUpdateOperationsInput */;
                      content?:
                        | string
                        | any /* circular reference to StringFieldUpdateOperationsInput */;
                      sent_at?:
                        | Date
                        | any /* circular reference to DateTimeFieldUpdateOperationsInput */;
                      updated_at?: any;
                      is_archived?: any;
                    };
                create:
                  | any /* circular reference to ThreadMessageCreateWithoutDiscussion_threadInput */
                  | any /* circular reference to ThreadMessageUncheckedCreateWithoutDiscussion_threadInput */;
              }
            | any /* circular reference to ThreadMessageUpsertWithWhereUniqueWithoutDiscussion_threadInput */;
          createMany?: any /* circular reference to ThreadMessageCreateManyDiscussion_threadInputEnvelope */;
          set?: any /* circular reference to ThreadMessageWhereUniqueInput */;
          disconnect?: any /* circular reference to ThreadMessageWhereUniqueInput */;
          delete?: any /* circular reference to ThreadMessageWhereUniqueInput */;
          connect?: any /* circular reference to ThreadMessageWhereUniqueInput */;
          update?:
            | {
                where: any /* circular reference to ThreadMessageWhereUniqueInput */;
                data:
                  | any /* circular reference to ThreadMessageUpdateWithoutDiscussion_threadInput */
                  | any /* circular reference to ThreadMessageUncheckedUpdateWithoutDiscussion_threadInput */;
              }
            | any /* circular reference to ThreadMessageUpdateWithWhereUniqueWithoutDiscussion_threadInput */;
          updateMany?:
            | {
                where: {
                  AND?: any /* circular reference to ThreadMessageScalarWhereInput */;
                  OR?: any /* circular reference to ThreadMessageScalarWhereInput */;
                  NOT?: any /* circular reference to ThreadMessageScalarWhereInput */;
                  message_id?: any /* circular reference to StringFilter */ | string;
                  thread_id?: any /* circular reference to StringFilter */ | string;
                  sender_id?: any /* circular reference to StringFilter */ | string;
                  content?: any /* circular reference to StringFilter */ | string;
                  sent_at?: any /* circular reference to DateTimeFilter */ | Date;
                  updated_at?: any;
                  is_archived?: any;
                };
                data:
                  | {
                      message_id?:
                        | string
                        | any /* circular reference to StringFieldUpdateOperationsInput */;
                      content?:
                        | string
                        | any /* circular reference to StringFieldUpdateOperationsInput */;
                      sent_at?:
                        | Date
                        | any /* circular reference to DateTimeFieldUpdateOperationsInput */;
                      updated_at?: any;
                      is_archived?: any;
                    }
                  | {
                      message_id?:
                        | string
                        | any /* circular reference to StringFieldUpdateOperationsInput */;
                      sender_id?:
                        | string
                        | any /* circular reference to StringFieldUpdateOperationsInput */;
                      content?:
                        | string
                        | any /* circular reference to StringFieldUpdateOperationsInput */;
                      sent_at?:
                        | Date
                        | any /* circular reference to DateTimeFieldUpdateOperationsInput */;
                      updated_at?: any;
                      is_archived?: any;
                    };
              }
            | any /* circular reference to ThreadMessageUpdateManyWithWhereWithoutDiscussion_threadInput */;
          deleteMany?: any /* circular reference to ThreadMessageScalarWhereInput */;
        };
      }
    | {
        thread_id?: string | any /* circular reference to StringFieldUpdateOperationsInput */;
        primary_participant?:
          | string
          | any /* circular reference to StringFieldUpdateOperationsInput */;
        secondary_participant?: any;
        created_on?: Date | any /* circular reference to DateTimeFieldUpdateOperationsInput */;
        closed_on?: any;
        is_flagged?: any;
        flagged_reason?: any;
        messages?: {
          create?:
            | any /* circular reference to ThreadMessageCreateWithoutDiscussion_threadInput */
            | any /* circular reference to ThreadMessageUncheckedCreateWithoutDiscussion_threadInput */;
          connectOrCreate?: any /* circular reference to ThreadMessageCreateOrConnectWithoutDiscussion_threadInput */;
          upsert?: any /* circular reference to ThreadMessageUpsertWithWhereUniqueWithoutDiscussion_threadInput */;
          createMany?: any /* circular reference to ThreadMessageCreateManyDiscussion_threadInputEnvelope */;
          set?: any /* circular reference to ThreadMessageWhereUniqueInput */;
          disconnect?: any /* circular reference to ThreadMessageWhereUniqueInput */;
          delete?: any /* circular reference to ThreadMessageWhereUniqueInput */;
          connect?: any /* circular reference to ThreadMessageWhereUniqueInput */;
          update?: any /* circular reference to ThreadMessageUpdateWithWhereUniqueWithoutDiscussion_threadInput */;
          updateMany?: any /* circular reference to ThreadMessageUpdateManyWithWhereWithoutDiscussion_threadInput */;
          deleteMany?: any /* circular reference to ThreadMessageScalarWhereInput */;
        };
      };
}

import { z } from "zod";

export const OneDiscussionThreadUpsertArgsSchema = z.object({
  where: z.any(),
  create: z.any(),
  update: z.any(),
});
