// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserProfileCreateOrConnectWithoutUser_notificationsInput {
  where: any;
  create: any;
}

import { z } from "zod";

export const UserProfileCreateOrConnectWithoutUser_notificationsInputSchema = z.object({
  where: z.any(),
  create: z.any(),
});
