// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserAccountOrderByWithAggregationInput {
  account_id?: any;
  owner_profile_id?: any;
  name?: any;
  created_at?: any;
  modified_at?: any;
  is_active?: any;
  _count?: any;
  _max?: any;
  _min?: any;
}

import { z } from "zod";

export const UserAccountOrderByWithAggregationInputSchema = z.object({
  account_id: z.any().optional(),
  owner_profile_id: z.any().optional(),
  name: z.any().optional(),
  created_at: z.any().optional(),
  modified_at: z.any().optional(),
  is_active: z.any().optional(),
  _count: z.any().optional(),
  _max: z.any().optional(),
  _min: z.any().optional(),
});
