// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserNotificationWhereUniqueInput {
  notification_id?: string;
  AND?: any;
  OR?: any;
  NOT?: any;
  recipient_profile_id?: any;
  sent_timestamp?: any;
  read_timestamp?: any;
  message?: any;
  notification_refs?: any;
  user_profile?: any;
}

import { z } from "zod";

export const UserNotificationWhereUniqueInputSchema = z.object({
  notification_id: z.string().optional(),
  AND: z.any().optional(),
  OR: z.array(z.any()).optional(),
  NOT: z.any().optional(),
  recipient_profile_id: z.any().optional(),
  sent_timestamp: z.any().optional(),
  read_timestamp: z.any().nullable().optional(),
  message: z.any().optional(),
  notification_refs: z.any().optional(),
  user_profile: z.any().optional(),
});
