// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserNotificationUpdateWithoutNotification_refsInput {
  notification_id: any;
  sent_timestamp: any;
  read_timestamp?: any;
  message: any;
  user_profile: any;
}

import { z } from "zod";

export const UserNotificationUpdateWithoutNotification_refsInputSchema = z.object({
  notification_id: z.string(),
  sent_timestamp: z.date(),
  read_timestamp: z.date().optional(),
  message: z.string(),
  user_profile: z.any(),
});
