// Auto-generated by prisma-dto-gen (refactored inline)

export interface NullableBoolFieldUpdateOperationsInput {
  set?: any;
}

import { z } from "zod";

export const NullableBoolFieldUpdateOperationsInputSchema = z.object({
  set: z.boolean().optional(),
});
