// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserProfileUpdateWithWhereUniqueWithoutCreated_by_profileInput {
  where: any;
  data: any;
}

import { z } from "zod";

export const UserProfileUpdateWithWhereUniqueWithoutCreated_by_profileInputSchema = z.object({
  where: z.any(),
  data: z.any(),
});
