// Auto-generated by prisma-dto-gen (refactored inline)

export interface TwoStepVerificationCountOrderByAggregateInput {
  verification_id?: any;
  profile_id?: any;
  code?: any;
  is_verified?: any;
  created_at?: any;
  verification_type?: any;
}

import { z } from "zod";

export const TwoStepVerificationCountOrderByAggregateInputSchema = z.object({
  verification_id: z.any().optional(),
  profile_id: z.any().optional(),
  code: z.any().optional(),
  is_verified: z.any().optional(),
  created_at: z.any().optional(),
  verification_type: z.any().optional(),
});
