// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserNotificationCreateManyUser_profileInputEnvelope {
  data: any;
  skipDuplicates?: boolean;
}

import { z } from "zod";

export const UserNotificationCreateManyUser_profileInputEnvelopeSchema = z.object({
  data: z.any(),
  skipDuplicates: z.boolean().optional(),
});
