// Auto-generated by prisma-dto-gen (refactored inline)

export interface ThreadMessageOrderByWithRelationInput {
  message_id: any;
  thread_id: any;
  sender_id: any;
  content: any;
  sent_at: any;
  updated_at: any;
  is_archived: any;
  discussion_thread: any;
  sender: any;
}

import { z } from "zod";

export const ThreadMessageOrderByWithRelationInputSchema = z.object({
  message_id: z.any(),
  thread_id: z.any(),
  sender_id: z.any(),
  content: z.any(),
  sent_at: z.any(),
  updated_at: z.any(),
  is_archived: z.any(),
  discussion_thread: z.any(),
  sender: z.any(),
});
