// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserNotificationCreateOrConnectWithoutNotification_refsInput {
  where: any;
  create: any;
}

import { z } from "zod";

export const UserNotificationCreateOrConnectWithoutNotification_refsInputSchema = z.object({
  where: z.any(),
  create: z.any(),
});
