// Auto-generated by prisma-dto-gen (refactored inline)

export interface DiscussionThreadUpdateWithWhereUniqueWithoutParticipant_twoInput {
  where: any;
  data: any;
}

import { z } from "zod";

export const DiscussionThreadUpdateWithWhereUniqueWithoutParticipant_twoInputSchema = z.object({
  where: z.any(),
  data: z.any(),
});
