// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrgRecordListRelationFilter {
  every?: any;
  some?: any;
  none?: any;
}

import { z } from "zod";

export const OrgRecordListRelationFilterSchema = z.object({
  every: z.any().optional(),
  some: z.any().optional(),
  none: z.any().optional(),
});
