// Auto-generated by prisma-dto-gen (refactored inline)

export interface EnumAccountLevelNullableFilter {
  equals?: any | null;
  in?: any | null;
  notIn?: any | null;
  not?: any | null;
}

import { z } from "zod";

export const EnumAccountLevelNullableFilterSchema = z.object({
  equals: z.enum(["BASIC", "PREMIUM", "ADMIN"]).nullable(),
  in: z.array(z.enum(["BASIC", "PREMIUM", "ADMIN"]).nullable()),
  notIn: z.array(z.enum(["BASIC", "PREMIUM", "ADMIN"]).nullable()),
  not: z.enum(["BASIC", "PREMIUM", "ADMIN"]).nullable(),
});
