// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrgRecordUncheckedUpdateInput {
  record_id?: any;
  organization_id?: any;
  title?: any;
  details?: any;
  created_on?: any;
  updated_on?: any;
}

import { z } from "zod";

export const OrgRecordUncheckedUpdateInputSchema = z.object({
  record_id: z.string().optional(),
  organization_id: z.string().optional(),
  title: z.string().optional(),
  details: z.string().nullable().optional(),
  created_on: z.date().optional(),
  updated_on: z.date().nullable().optional(),
});
