// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrgMembershipCreateInput {
  membership_id: string;
  joined_on: Date;
  is_active?: any;
  organization: any;
  user_profile: any;
}

import { z } from "zod";

export const OrgMembershipCreateInputSchema = z.object({
  membership_id: z.string(),
  joined_on: z.date(),
  is_active: z.boolean().optional(),
  organization: z.any(),
  user_profile: z.any(),
});
