// Auto-generated by prisma-dto-gen (refactored inline)

export interface BoolNullableFilter {
  equals?: any | null;
  not?: any | null;
}

import { z } from "zod";

export const BoolNullableFilterSchema = z.object({
  equals: z.boolean().nullable(),
  not: z.boolean().nullable(),
});
