// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserAccountUncheckedUpdateManyWithoutUser_profileInput {
  account_id: any;
  name: any;
  created_at: any;
  modified_at?: any | null;
  is_active: any;
}

import { z } from "zod";

export const UserAccountUncheckedUpdateManyWithoutUser_profileInputSchema = z.object({
  account_id: z.string(),
  name: z.string(),
  created_at: z.date(),
  modified_at: z.date().nullable(),
  is_active: z.boolean(),
});
