// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserProfileListRelationFilter {
  every: any;
  some: any;
  none: any;
}

import { z } from "zod";

export const UserProfileListRelationFilterSchema = z.object({
  every: z.any(),
  some: z.any(),
  none: z.any(),
});
