// Auto-generated by prisma-dto-gen (refactored inline)

export interface DiscussionThreadUpdateManyMutationInput {
  thread_id: any;
  created_on: any;
  closed_on?: any | null;
  is_flagged?: any | null;
  flagged_reason?: any | null;
}

import { z } from "zod";

export const DiscussionThreadUpdateManyMutationInputSchema = z.object({
  thread_id: z.string(),
  created_on: z.date(),
  closed_on: z.date().nullable(),
  is_flagged: z.boolean().nullable(),
  flagged_reason: z.string().nullable(),
});
