// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrgMembershipUncheckedUpdateWithoutOrganizationInput {
  membership_id?: any;
  profile_id?: any;
  joined_on?: any;
  is_active?: any;
}

import { z } from "zod";

export const OrgMembershipUncheckedUpdateWithoutOrganizationInputSchema = z.object({
  membership_id: z.string().optional(),
  profile_id: z.string().optional(),
  joined_on: z.date().optional(),
  is_active: z.boolean().nullable().optional(),
});
