// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrgMembershipCreateOrConnectWithoutUser_profileInput {
  where: any;
  create: any;
}

import { z } from "zod";

export const OrgMembershipCreateOrConnectWithoutUser_profileInputSchema = z.object({
  where: z.any(),
  create: z.any(),
});
