// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrganizationUncheckedUpdateManyInput {
  organization_id: any;
  name: any;
  description?: any;
  created_on: any;
  updated_on?: any;
  is_active?: any;
}

import { z } from "zod";

export const OrganizationUncheckedUpdateManyInputSchema = z.object({
  organization_id: z.string(),
  name: z.string(),
  description: z.string().optional(),
  created_on: z.date(),
  updated_on: z.date().optional(),
  is_active: z.boolean().optional(),
});
