// Auto-generated by prisma-dto-gen (refactored inline)

export interface NestedDateTimeNullableWithAggregatesFilter {
  equals?: any;
  in?: any;
  notIn?: any;
  lt?: any;
  lte?: any;
  gt?: any;
  gte?: any;
  not?: any;
  _count?: any;
  _min?: any;
  _max?: any;
}

import { z } from "zod";

export const NestedDateTimeNullableWithAggregatesFilterSchema = z.object({
  equals: z.date().nullable().optional(),
  in: z.array(z.date()).nullable().optional(),
  notIn: z.array(z.date()).nullable().optional(),
  lt: z.date().optional(),
  lte: z.date().optional(),
  gt: z.date().optional(),
  gte: z.date().optional(),
  not: z.date().nullable().optional(),
  _count: z.any().optional(),
  _min: z.any().optional(),
  _max: z.any().optional(),
});
