// Auto-generated by prisma-dto-gen (refactored inline)

export interface ThreadMessageUncheckedUpdateWithoutSenderInput {
  message_id?: any;
  thread_id?: any;
  content?: any;
  sent_at?: any;
  updated_at?: any;
  is_archived?: any;
}

import { z } from "zod";

export const ThreadMessageUncheckedUpdateWithoutSenderInputSchema = z.object({
  message_id: z.string().optional(),
  thread_id: z.string().optional(),
  content: z.string().optional(),
  sent_at: z.date().optional(),
  updated_at: z.date().nullable().optional(),
  is_archived: z.boolean().nullable().optional(),
});
