// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserProfileCreateNestedOneWithoutUser_accountsInput {
  create: any;
  connectOrCreate: any;
  connect: any;
}

import { z } from "zod";

export const UserProfileCreateNestedOneWithoutUser_accountsInputSchema = z.object({
  create: z.any(),
  connectOrCreate: z.any(),
  connect: z.any(),
});
