// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrgRecordWhereUniqueInput {
  record_id: string;
  AND: any;
  OR: any;
  NOT: any;
  organization_id: any;
  title: any;
  details?: any | null;
  created_on: any;
  updated_on?: any | null;
  organization: any;
}

import { z } from "zod";

export const OrgRecordWhereUniqueInputSchema = z.object({
  record_id: z.string(),
  AND: z.any(),
  OR: z.array(z.any()),
  NOT: z.any(),
  organization_id: z.any(),
  title: z.any(),
  details: z.any().nullable(),
  created_on: z.any(),
  updated_on: z.any().nullable(),
  organization: z.any(),
});
