// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserDocumentCreateOrConnectWithoutCommentsInput {
  where: any;
  create: any;
}

import { z } from "zod";

export const UserDocumentCreateOrConnectWithoutCommentsInputSchema = z.object({
  where: z.any(),
  create: z.any(),
});
