// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrgMembershipCreateManyUser_profileInputEnvelope {
  data: any;
  skipDuplicates: boolean;
}

import { z } from "zod";

export const OrgMembershipCreateManyUser_profileInputEnvelopeSchema = z.object({
  data: z.any(),
  skipDuplicates: z.boolean(),
});
