// Auto-generated by prisma-dto-gen (refactored inline)

export interface NestedEnumAccountLevelNullableFilter {
  equals?: any;
  in?: any;
  notIn?: any;
  not?: any;
}

import { z } from "zod";

export const NestedEnumAccountLevelNullableFilterSchema = z.object({
  equals: z.enum(["BASIC", "PREMIUM", "ADMIN"]).nullable().optional(),
  in: z
    .array(z.enum(["BASIC", "PREMIUM", "ADMIN"]))
    .nullable()
    .optional(),
  notIn: z
    .array(z.enum(["BASIC", "PREMIUM", "ADMIN"]))
    .nullable()
    .optional(),
  not: z.enum(["BASIC", "PREMIUM", "ADMIN"]).nullable().optional(),
});
