// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrganizationUpsertWithoutRecordsInput {
  update: any;
  create: any;
  where: any;
}

import { z } from "zod";

export const OrganizationUpsertWithoutRecordsInputSchema = z.object({
  update: z.any(),
  create: z.any(),
  where: z.any(),
});
