// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserAccountScalarWhereWithAggregatesInput {
  AND: any;
  OR: any;
  NOT: any;
  account_id: any;
  owner_profile_id: any;
  name: any;
  created_at: any;
  modified_at?: any;
  is_active: any;
}

import { z } from "zod";

export const UserAccountScalarWhereWithAggregatesInputSchema = z.object({
  AND: z.any(),
  OR: z.array(z.any()),
  NOT: z.any(),
  account_id: z.any(),
  owner_profile_id: z.any(),
  name: z.any(),
  created_at: z.any(),
  modified_at: z.any().optional(),
  is_active: z.any(),
});
