// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrgRecordWhereInput {
  AND?:
    | {
        AND?: any /* circular reference to OrgRecordWhereInput */;
        OR?: any /* circular reference to OrgRecordWhereInput */;
        NOT?: any /* circular reference to OrgRecordWhereInput */;
        record_id?: any;
        organization_id?: any;
        title?: any;
        details?: any;
        created_on?: any;
        updated_on?: any;
        organization?: any;
      }
    | any /* circular reference to OrgRecordWhereInput */;
  OR?: any /* circular reference to OrgRecordWhereInput */;
  NOT?: any /* circular reference to OrgRecordWhereInput */;
  record_id?: any;
  organization_id?: any;
  title?: any;
  details?: any;
  created_on?: any;
  updated_on?: any;
  organization?: any;
}

import { z } from "zod";

export const OrgRecordWhereInputSchema = z.object({
  AND: z.any().optional(),
  OR: z.array(z.any()).optional(),
  NOT: z.any().optional(),
  record_id: z.any().optional(),
  organization_id: z.any().optional(),
  title: z.any().optional(),
  details: z.any().nullable().optional(),
  created_on: z.any().optional(),
  updated_on: z.any().nullable().optional(),
  organization: z.any().optional(),
});
