// Auto-generated by prisma-dto-gen (refactored inline)

export interface ThreadMessageUncheckedUpdateManyWithoutSenderNestedInput {
  create: any;
  connectOrCreate: any;
  upsert: any;
  createMany: any;
  set: any;
  disconnect: any;
  delete: any;
  connect: any;
  update: any;
  updateMany: any;
  deleteMany: any;
}

import { z } from "zod";

export const ThreadMessageUncheckedUpdateManyWithoutSenderNestedInputSchema = z.object({
  create: z.any(),
  connectOrCreate: z.any(),
  upsert: z.any(),
  createMany: z.any(),
  set: z.any(),
  disconnect: z.any(),
  delete: z.any(),
  connect: z.any(),
  update: z.any(),
  updateMany: z.any(),
  deleteMany: z.any(),
});
