// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrgEventMaxOrderByAggregateInput {
  org_event_id?: any;
  organization_id?: any;
  event_name?: any;
  start_time?: any;
  end_time?: any;
  location?: any;
}

import { z } from "zod";

export const OrgEventMaxOrderByAggregateInputSchema = z.object({
  org_event_id: z.any().optional(),
  organization_id: z.any().optional(),
  event_name: z.any().optional(),
  start_time: z.any().optional(),
  end_time: z.any().optional(),
  location: z.any().optional(),
});
