// Auto-generated by prisma-dto-gen (refactored inline)

export interface NotificationReferenceUncheckedCreateInput {
  notification_reference_id: string;
  notification_id: string;
  referenced_entity_id: string;
  status: "DRAFT" | "REVIEW" | "PUBLISHED" | "ARCHIVED";
  archived?: any;
}

import { z } from "zod";

export const NotificationReferenceUncheckedCreateInputSchema = z.object({
  notification_reference_id: z.string(),
  notification_id: z.string(),
  referenced_entity_id: z.string(),
  status: z.enum(["DRAFT", "REVIEW", "PUBLISHED", "ARCHIVED"]),
  archived: z.boolean().optional(),
});
