// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserNotificationUpdateManyWithWhereWithoutUser_profileInput {
  where: any;
  data: any;
}

import { z } from "zod";

export const UserNotificationUpdateManyWithWhereWithoutUser_profileInputSchema = z.object({
  where: z.any(),
  data: z.any(),
});
