// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserProfileOrderByRelationAggregateInput {
  _count: any;
}

import { z } from "zod";

export const UserProfileOrderByRelationAggregateInputSchema = z.object({
  _count: z.any(),
});
