// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserNotificationWhereInput {
  AND?:
    | {
        AND?: any /* circular reference to UserNotificationWhereInput */;
        OR?: any /* circular reference to UserNotificationWhereInput */;
        NOT?: any /* circular reference to UserNotificationWhereInput */;
        notification_id?: any;
        recipient_profile_id?: any;
        sent_timestamp?: any;
        read_timestamp?: any;
        message?: any;
        notification_refs?: any;
        user_profile?: any;
      }
    | any /* circular reference to UserNotificationWhereInput */;
  OR?: any /* circular reference to UserNotificationWhereInput */;
  NOT?: any /* circular reference to UserNotificationWhereInput */;
  notification_id?: any;
  recipient_profile_id?: any;
  sent_timestamp?: any;
  read_timestamp?: any;
  message?: any;
  notification_refs?: any;
  user_profile?: any;
}

import { z } from "zod";

export const UserNotificationWhereInputSchema = z.object({
  AND: z.any().optional(),
  OR: z.array(z.any()).optional(),
  NOT: z.any().optional(),
  notification_id: z.any().optional(),
  recipient_profile_id: z.any().optional(),
  sent_timestamp: z.any().optional(),
  read_timestamp: z.any().nullable().optional(),
  message: z.any().optional(),
  notification_refs: z.any().optional(),
  user_profile: z.any().optional(),
});
