// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrgRecordOrderByWithRelationInput {
  record_id?: any;
  organization_id?: any;
  title?: any;
  details?: any;
  created_on?: any;
  updated_on?: any;
  organization?: any;
}

import { z } from "zod";

export const OrgRecordOrderByWithRelationInputSchema = z.object({
  record_id: z.any().optional(),
  organization_id: z.any().optional(),
  title: z.any().optional(),
  details: z.any().optional(),
  created_on: z.any().optional(),
  updated_on: z.any().optional(),
  organization: z.any().optional(),
});
