// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserProfileCreateNestedOneWithoutUser_commentsInput {
  create?: any;
  connectOrCreate?: any;
  connect?: any;
}

import { z } from "zod";

export const UserProfileCreateNestedOneWithoutUser_commentsInputSchema = z.object({
  create: z.any().optional(),
  connectOrCreate: z.any().optional(),
  connect: z.any().optional(),
});
