// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrgEventOrderByRelationAggregateInput {
  _count: any;
}

import { z } from "zod";

export const OrgEventOrderByRelationAggregateInputSchema = z.object({
  _count: z.any(),
});
