// Auto-generated by prisma-dto-gen (refactored inline)

type Decimal = { valueOf(): string };

export interface DecimalFieldUpdateOperationsInput {
  set: Decimal;
  increment: Decimal;
  decrement: Decimal;
  multiply: Decimal;
  divide: Decimal;
}

import { z } from "zod";

export const DecimalFieldUpdateOperationsInputSchema = z.object({
  set: z.any(),
  increment: z.any(),
  decrement: z.any(),
  multiply: z.any(),
  divide: z.any(),
});
