// Auto-generated by prisma-dto-gen (refactored inline)

export interface NestedIntNullableFilter {
  equals?: any | null;
  in?: any | null;
  notIn?: any | null;
  lt: any;
  lte: any;
  gt: any;
  gte: any;
  not?: any | null;
}

import { z } from "zod";

export const NestedIntNullableFilterSchema = z.object({
  equals: z.number().nullable(),
  in: z.array(z.number()).nullable(),
  notIn: z.array(z.number()).nullable(),
  lt: z.number(),
  lte: z.number(),
  gt: z.number(),
  gte: z.number(),
  not: z.number().nullable(),
});
