// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrgEventScalarWhereWithAggregatesInput {
  AND: any;
  OR: any;
  NOT: any;
  org_event_id: any;
  organization_id: any;
  event_name: any;
  start_time: any;
  end_time?: any | null;
  location?: any | null;
}

import { z } from "zod";

export const OrgEventScalarWhereWithAggregatesInputSchema = z.object({
  AND: z.any(),
  OR: z.array(z.any()),
  NOT: z.any(),
  org_event_id: z.any(),
  organization_id: z.any(),
  event_name: z.any(),
  start_time: z.any(),
  end_time: z.any().nullable(),
  location: z.any().nullable(),
});
