// Auto-generated by prisma-dto-gen (refactored inline)

export interface DiscussionThreadUncheckedCreateInput {
  thread_id: string;
  primary_participant: string;
  secondary_participant?: any;
  created_on: Date;
  closed_on?: any;
  is_flagged?: any;
  flagged_reason?: any;
  messages: any;
}

import { z } from "zod";

export const DiscussionThreadUncheckedCreateInputSchema = z.object({
  thread_id: z.string(),
  primary_participant: z.string(),
  secondary_participant: z.string().optional(),
  created_on: z.date(),
  closed_on: z.date().optional(),
  is_flagged: z.boolean().optional(),
  flagged_reason: z.string().optional(),
  messages: z.any(),
});
