// Auto-generated by prisma-dto-gen (refactored inline)

export interface EnumDocumentStatusWithAggregatesFilter {
  equals: any;
  in: any;
  notIn: any;
  not: any;
  _count: any;
  _min: any;
  _max: any;
}

import { z } from "zod";

export const EnumDocumentStatusWithAggregatesFilterSchema = z.object({
  equals: z.enum(["DRAFT", "REVIEW", "PUBLISHED", "ARCHIVED"]),
  in: z.array(z.enum(["DRAFT", "REVIEW", "PUBLISHED", "ARCHIVED"])),
  notIn: z.array(z.enum(["DRAFT", "REVIEW", "PUBLISHED", "ARCHIVED"])),
  not: z.enum(["DRAFT", "REVIEW", "PUBLISHED", "ARCHIVED"]),
  _count: z.any(),
  _min: z.any(),
  _max: z.any(),
});
