// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserCommentUpsertWithWhereUniqueWithoutUser_profileInput {
  where: any;
  update: any;
  create: any;
}

import { z } from "zod";

export const UserCommentUpsertWithWhereUniqueWithoutUser_profileInputSchema = z.object({
  where: z.any(),
  update: z.any(),
  create: z.any(),
});
