// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrganizationScalarWhereWithAggregatesInput {
  AND?: any;
  OR?: any;
  NOT?: any;
  organization_id?: any;
  name?: any;
  description?: any;
  created_on?: any;
  updated_on?: any;
  is_active?: any;
}

import { z } from "zod";

export const OrganizationScalarWhereWithAggregatesInputSchema = z.object({
  AND: z.any().optional(),
  OR: z.array(z.any()).optional(),
  NOT: z.any().optional(),
  organization_id: z.any().optional(),
  name: z.any().optional(),
  description: z.any().nullable().optional(),
  created_on: z.any().optional(),
  updated_on: z.any().nullable().optional(),
  is_active: z.any().nullable().optional(),
});
