// Auto-generated by prisma-dto-gen (refactored inline)

export interface ThreadMessageCreateWithoutDiscussion_threadInput {
  message_id: string;
  content: string;
  sent_at: Date;
  updated_at?: any;
  is_archived?: any;
  sender: any;
}

import { z } from "zod";

export const ThreadMessageCreateWithoutDiscussion_threadInputSchema = z.object({
  message_id: z.string(),
  content: z.string(),
  sent_at: z.date(),
  updated_at: z.date().optional(),
  is_archived: z.boolean().optional(),
  sender: z.any(),
});
