// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserCommentUpdateWithWhereUniqueWithoutUser_profileInput {
  where: any;
  data: any;
}

import { z } from "zod";

export const UserCommentUpdateWithWhereUniqueWithoutUser_profileInputSchema = z.object({
  where: z.any(),
  data: z.any(),
});
