// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserCommentScalarWhereInput {
  AND: any;
  OR: any;
  NOT: any;
  comment_id: any;
  document_id: any;
  commenter_id: any;
  text: any;
  created_at: any;
  edited_at?: any | null;
  is_deleted?: any | null;
}

import { z } from "zod";

export const UserCommentScalarWhereInputSchema = z.object({
  AND: z.any(),
  OR: z.array(z.any()),
  NOT: z.any(),
  comment_id: z.any(),
  document_id: z.any(),
  commenter_id: z.any(),
  text: z.any(),
  created_at: z.any(),
  edited_at: z.any().nullable(),
  is_deleted: z.any().nullable(),
});
