// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrgRecordUncheckedCreateWithoutOrganizationInput {
  record_id: string;
  title: string;
  details?: any;
  created_on: Date;
  updated_on?: any;
}

import { z } from "zod";

export const OrgRecordUncheckedCreateWithoutOrganizationInputSchema = z.object({
  record_id: z.string(),
  title: z.string(),
  details: z.string().optional(),
  created_on: z.date(),
  updated_on: z.date().optional(),
});
