// Auto-generated by prisma-dto-gen (refactored inline)

export interface ThreadMessageUpdateWithWhereUniqueWithoutDiscussion_threadInput {
  where: any;
  data: any;
}

import { z } from "zod";

export const ThreadMessageUpdateWithWhereUniqueWithoutDiscussion_threadInputSchema = z.object({
  where: z.any(),
  data: z.any(),
});
