// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserProfileCreateNestedOneWithoutSent_messagesInput {
  create: any;
  connectOrCreate: any;
  connect: any;
}

import { z } from "zod";

export const UserProfileCreateNestedOneWithoutSent_messagesInputSchema = z.object({
  create: z.any(),
  connectOrCreate: z.any(),
  connect: z.any(),
});
