// Auto-generated by prisma-dto-gen (refactored inline)

export interface BoolNullableWithAggregatesFilter {
  equals?: any | null;
  not?: any | null;
  _count: any;
  _min: any;
  _max: any;
}

import { z } from "zod";

export const BoolNullableWithAggregatesFilterSchema = z.object({
  equals: z.boolean().nullable(),
  not: z.boolean().nullable(),
  _count: z.any(),
  _min: z.any(),
  _max: z.any(),
});
