// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrgRecordWhereInput {
  AND: any;
  OR: any;
  NOT: any;
  record_id: any;
  organization_id: any;
  title: any;
  details?: any | null;
  created_on: any;
  updated_on?: any | null;
  organization: any;
}

import { z } from "zod";

export const OrgRecordWhereInputSchema = z.object({
  AND: z.any(),
  OR: z.array(z.any()),
  NOT: z.any(),
  record_id: z.any(),
  organization_id: z.any(),
  title: z.any(),
  details: z.any().nullable(),
  created_on: z.any(),
  updated_on: z.any().nullable(),
  organization: z.any(),
});
