// Auto-generated by prisma-dto-gen (refactored inline)

export interface DateTimeNullableWithAggregatesFilter {
  equals?: any;
  in?: any;
  notIn?: any;
  lt: any;
  lte: any;
  gt: any;
  gte: any;
  not?: any;
  _count: any;
  _min: any;
  _max: any;
}

import { z } from "zod";

export const DateTimeNullableWithAggregatesFilterSchema = z.object({
  equals: z.date().optional(),
  in: z.array(z.date()).optional(),
  notIn: z.array(z.date()).optional(),
  lt: z.date(),
  lte: z.date(),
  gt: z.date(),
  gte: z.date(),
  not: z.date().optional(),
  _count: z.any(),
  _min: z.any(),
  _max: z.any(),
});
