// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserAccountWhereUniqueInput {
  account_id?: string;
  AND?: any;
  OR?: any;
  NOT?: any;
  owner_profile_id?: any;
  name?: any;
  created_at?: any;
  modified_at?: any;
  is_active?: any;
  user_profile?: any;
}

import { z } from "zod";

export const UserAccountWhereUniqueInputSchema = z.object({
  account_id: z.string().optional(),
  AND: z.any().optional(),
  OR: z.array(z.any()).optional(),
  NOT: z.any().optional(),
  owner_profile_id: z.any().optional(),
  name: z.any().optional(),
  created_at: z.any().optional(),
  modified_at: z.any().nullable().optional(),
  is_active: z.any().optional(),
  user_profile: z.any().optional(),
});
