// Auto-generated by prisma-dto-gen (refactored inline)

export interface ThreadMessageUpdateWithWhereUniqueWithoutSenderInput {
  where: any;
  data: any;
}

import { z } from "zod";

export const ThreadMessageUpdateWithWhereUniqueWithoutSenderInputSchema = z.object({
  where: z.any(),
  data: z.any(),
});
