// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserProfileUpdateToOneWithWhereWithoutProfiles_createdInput {
  where: any;
  data: any;
}

import { z } from "zod";

export const UserProfileUpdateToOneWithWhereWithoutProfiles_createdInputSchema = z.object({
  where: z.any(),
  data: z.any(),
});
