// Auto-generated by prisma-dto-gen (refactored inline)

export interface TwoStepVerificationMaxOrderByAggregateInput {
  verification_id: any;
  profile_id: any;
  code: any;
  is_verified: any;
  created_at: any;
  verification_type: any;
}

import { z } from "zod";

export const TwoStepVerificationMaxOrderByAggregateInputSchema = z.object({
  verification_id: z.any(),
  profile_id: z.any(),
  code: z.any(),
  is_verified: z.any(),
  created_at: z.any(),
  verification_type: z.any(),
});
