// Auto-generated by prisma-dto-gen (refactored inline)

type Decimal = { valueOf(): string };

export interface NestedDecimalWithAggregatesFilter {
  equals: any;
  in: any;
  notIn: any;
  lt: any;
  lte: any;
  gt: any;
  gte: any;
  not: any;
  _count: any;
  _avg: any;
  _sum: any;
  _min: any;
  _max: any;
}

import { z } from "zod";

export const NestedDecimalWithAggregatesFilterSchema = z.object({
  equals: z.any(),
  in: z.array(z.any()),
  notIn: z.array(z.any()),
  lt: z.any(),
  lte: z.any(),
  gt: z.any(),
  gte: z.any(),
  not: z.any(),
  _count: z.any(),
  _avg: z.any(),
  _sum: z.any(),
  _min: z.any(),
  _max: z.any(),
});
