// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserCommentCreateWithoutUser_profileInput {
  comment_id?: string;
  text: string;
  created_at?: Date;
  edited_at?: any;
  is_deleted?: any;
  user_document: any;
}

import { z } from "zod";

export const UserCommentCreateWithoutUser_profileInputSchema = z.object({
  comment_id: z.string().optional(),
  text: z.string(),
  created_at: z.date().optional(),
  edited_at: z.date().nullable().optional(),
  is_deleted: z.boolean().nullable().optional(),
  user_document: z.any(),
});
