// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserAccountUpdateInput {
  account_id: any;
  name: any;
  created_at: any;
  modified_at?: any;
  is_active: any;
  user_profile: any;
}

import { z } from "zod";

export const UserAccountUpdateInputSchema = z.object({
  account_id: z.string(),
  name: z.string(),
  created_at: z.date(),
  modified_at: z.date().optional(),
  is_active: z.boolean(),
  user_profile: z.any(),
});
