// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrgEventUpdateManyWithWhereWithoutOrganizationInput {
  where: any;
  data: any;
}

import { z } from "zod";

export const OrgEventUpdateManyWithWhereWithoutOrganizationInputSchema = z.object({
  where: z.any(),
  data: z.any(),
});
