// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrgEventCreateInput {
  org_event_id?: string;
  event_name: string;
  start_time: Date;
  end_time?: any;
  location?: any;
  organization: any;
}

import { z } from "zod";

export const OrgEventCreateInputSchema = z.object({
  org_event_id: z.string().optional(),
  event_name: z.string(),
  start_time: z.date(),
  end_time: z.date().nullable().optional(),
  location: z.string().nullable().optional(),
  organization: z.any(),
});
