// Auto-generated by prisma-dto-gen (refactored inline)

export interface TwoStepVerificationUpdateInput {
  verification_id?: any;
  code?: any;
  is_verified?: any;
  created_at?: any;
  verification_type?: any;
  user_profile?: any;
}

import { z } from "zod";

export const TwoStepVerificationUpdateInputSchema = z.object({
  verification_id: z.string().optional(),
  code: z.string().nullable().optional(),
  is_verified: z.boolean().optional(),
  created_at: z.date().optional(),
  verification_type: z.enum(["EMAIL", "SMS", "PUSH"]).optional(),
  user_profile: z.any().optional(),
});
