// Auto-generated by prisma-dto-gen (refactored inline)

type Decimal = { valueOf(): string };

export interface PaymentGroupByOutputTypeOutput {
  payment_id: string;
  payer_id: string;
  amount: Decimal;
  paid_at: Date;
  status: "DRAFT" | "REVIEW" | "PUBLISHED" | "ARCHIVED";
  reference_note?: string | null;
  _count?: any | null;
  _avg?: any | null;
  _sum?: any | null;
  _min?: any | null;
  _max?: any | null;
}

import { z } from "zod";

export const PaymentGroupByOutputTypeOutputSchema = z.object({
  payment_id: z.string(),
  payer_id: z.string(),
  amount: z.any(),
  paid_at: z.date(),
  status: z.enum(["DRAFT", "REVIEW", "PUBLISHED", "ARCHIVED"]),
  reference_note: z.string().nullable(),
  _count: z.any().nullable(),
  _avg: z.any().nullable(),
  _sum: z.any().nullable(),
  _min: z.any().nullable(),
  _max: z.any().nullable(),
});
