// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserNotificationMaxAggregateOutputTypeOutput {
  notification_id?: string;
  recipient_profile_id?: string;
  sent_timestamp?: Date;
  read_timestamp?: Date;
  message?: string;
}

import { z } from "zod";

export const UserNotificationMaxAggregateOutputTypeOutputSchema = z.object({
  notification_id: z.string().optional(),
  recipient_profile_id: z.string().optional(),
  sent_timestamp: z.date().optional(),
  read_timestamp: z.date().optional(),
  message: z.string().optional(),
});
