// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserNotificationCountOutputTypeOutput {
  notification_refs: number;
}

import { z } from "zod";

export const UserNotificationCountOutputTypeOutputSchema = z.object({
  notification_refs: z.number(),
});
