// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrganizationMaxAggregateOutputTypeOutput {
  organization_id?: string;
  name?: string;
  description?: string;
  created_on?: Date;
  updated_on?: Date;
  is_active?: boolean;
}

import { z } from "zod";

export const OrganizationMaxAggregateOutputTypeOutputSchema = z.object({
  organization_id: z.string().optional(),
  name: z.string().optional(),
  description: z.string().optional(),
  created_on: z.date().optional(),
  updated_on: z.date().optional(),
  is_active: z.boolean().optional(),
});
