// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserNotificationGroupByOutputTypeOutput {
  notification_id: string;
  recipient_profile_id: string;
  sent_timestamp: Date;
  read_timestamp: Date;
  message: string;
  _count: any;
  _min: any;
  _max: any;
}

import { z } from "zod";

export const UserNotificationGroupByOutputTypeOutputSchema = z.object({
  notification_id: z.string(),
  recipient_profile_id: z.string(),
  sent_timestamp: z.date(),
  read_timestamp: z.date().nullable(),
  message: z.string(),
  _count: z.any().nullable(),
  _min: z.any().nullable(),
  _max: z.any().nullable(),
});
