// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrgEventMinAggregateOutputTypeOutput {
  org_event_id: string;
  organization_id: string;
  event_name: string;
  start_time: Date;
  end_time: Date;
  location: string;
}

import { z } from "zod";

export const OrgEventMinAggregateOutputTypeOutputSchema = z.object({
  org_event_id: z.string().nullable(),
  organization_id: z.string().nullable(),
  event_name: z.string().nullable(),
  start_time: z.date().nullable(),
  end_time: z.date().nullable(),
  location: z.string().nullable(),
});
