// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrganizationGroupByOutputTypeOutput {
  organization_id: string;
  name: string;
  description?: string;
  created_on: Date;
  updated_on?: Date;
  is_active?: boolean;
  _count?: any;
  _min?: any;
  _max?: any;
}

import { z } from "zod";

export const OrganizationGroupByOutputTypeOutputSchema = z.object({
  organization_id: z.string(),
  name: z.string(),
  description: z.string().optional(),
  created_on: z.date(),
  updated_on: z.date().optional(),
  is_active: z.boolean().optional(),
  _count: z.any().optional(),
  _min: z.any().optional(),
  _max: z.any().optional(),
});
