// Auto-generated by prisma-dto-gen (refactored inline)

export interface UserAccountCountAggregateOutputTypeOutput {
  account_id: number;
  owner_profile_id: number;
  name: number;
  created_at: number;
  modified_at: number;
  is_active: number;
  _all: number;
}

import { z } from "zod";

export const UserAccountCountAggregateOutputTypeOutputSchema = z.object({
  account_id: z.number(),
  owner_profile_id: z.number(),
  name: z.number(),
  created_at: z.number(),
  modified_at: z.number(),
  is_active: z.number(),
  _all: z.number(),
});
