// Auto-generated by prisma-dto-gen (refactored inline)

export interface AggregateOrgMembershipOutput {
  _count?: any | null;
  _min?: any | null;
  _max?: any | null;
}

import { z } from "zod";

export const AggregateOrgMembershipOutputSchema = z.object({
  _count: z.any().nullable(),
  _min: z.any().nullable(),
  _max: z.any().nullable(),
});
