// Auto-generated by prisma-dto-gen (refactored inline)

export interface OrgRecordMaxAggregateOutputTypeOutput {
  record_id?: string | null;
  organization_id?: string | null;
  title?: string | null;
  details?: string | null;
  created_on?: Date | null;
  updated_on?: Date | null;
}

import { z } from "zod";

export const OrgRecordMaxAggregateOutputTypeOutputSchema = z.object({
  record_id: z.string().nullable(),
  organization_id: z.string().nullable(),
  title: z.string().nullable(),
  details: z.string().nullable(),
  created_on: z.date().nullable(),
  updated_on: z.date().nullable(),
});
