// Auto-generated by prisma-dto-gen (refactored inline)

export interface DiscussionThreadMaxAggregateOutputTypeOutput {
  thread_id?: string;
  primary_participant?: string;
  secondary_participant?: string;
  created_on?: Date;
  closed_on?: Date;
  is_flagged?: boolean;
  flagged_reason?: string;
}

import { z } from "zod";

export const DiscussionThreadMaxAggregateOutputTypeOutputSchema = z.object({
  thread_id: z.string().optional(),
  primary_participant: z.string().optional(),
  secondary_participant: z.string().optional(),
  created_on: z.date().optional(),
  closed_on: z.date().optional(),
  is_flagged: z.boolean().optional(),
  flagged_reason: z.string().optional(),
});
