// Auto-generated by prisma-dto-gen

import { User } from "./User.ts";
import { AggregateUser } from "./AggregateUser.ts";
import { UserGroupByOutputType } from "./UserGroupByOutputType.ts";

export interface Query {
  findFirstUser?: User | null;
  findFirstUserOrThrow?: User | null;
  findManyUser: User[];
  aggregateUser: AggregateUser;
  groupByUser: UserGroupByOutputType[];
  findUniqueUser?: User | null;
  findUniqueUserOrThrow?: User | null;
}
