// Auto-generated by prisma-dto-gen

import { z } from "zod";
import { UserSchema } from "./User.schema.ts";
import { AggregateUserSchema } from "./AggregateUser.schema.ts";
import { UserGroupByOutputTypeSchema } from "./UserGroupByOutputType.schema.ts";

export const QuerySchema = z.object({
  findFirstUser: UserSchema.nullable(),
  findFirstUserOrThrow: UserSchema.nullable(),
  findManyUser: z.array(UserSchema),
  aggregateUser: AggregateUserSchema,
  groupByUser: z.array(UserGroupByOutputTypeSchema),
  findUniqueUser: UserSchema.nullable(),
  findUniqueUserOrThrow: UserSchema.nullable(),
});
