// Auto-generated by prisma-dto-gen (refactored inline)

type JsonValue =
      | string
      | number
      | boolean
      | { [key: string]: JsonValue }
      | JsonValue[]
      | null;

export interface MutationOutput {
  createOneUser: {
  id: number;
  name: string;
  email: string;
};
  upsertOneUser: any /* circular reference to User */;
  createManyUser: any;
  createManyUserAndReturn: any;
  deleteOneUser?: any /* circular reference to User */ | null;
  updateOneUser?: any /* circular reference to User */ | null;
  updateManyUser: any;
  deleteManyUser: any;
  executeRaw: JsonValue;
  queryRaw: JsonValue;
}